{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "laser_assembler",
    "version": "1.7.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "sensor_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "tf",
          "version": {
            "requires": "1.13.2"
          }
        }
      ],
      "files": [
        {
          "name": "laser_assembler-1.7.8.jar",
          "url": "laser_assembler-1.7.8.jar",
          "size": 3604,
          "sha512": "671649fbeb7e82d766c2b1115a331f0f5aa62e21ba53cbbfb683c255127efdcc10bab79b9483a50be722fda4d84031c7be350ba81cf802305ae33b29ff14ac43",
          "sha256": "77dc7e5a5a33d5b7d4c6f77cd6160b34b0b02223f85ccd42e27383c4c1bec7f5",
          "sha1": "bdaa0fea6fb748a0f7d02e45e4378e6a3974d238",
          "md5": "bb13f88116f0e068ae8cd78323a41eab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "sensor_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "tf",
          "version": {
            "requires": "1.13.2"
          }
        }
      ],
      "files": [
        {
          "name": "laser_assembler-1.7.8.jar",
          "url": "laser_assembler-1.7.8.jar",
          "size": 3604,
          "sha512": "671649fbeb7e82d766c2b1115a331f0f5aa62e21ba53cbbfb683c255127efdcc10bab79b9483a50be722fda4d84031c7be350ba81cf802305ae33b29ff14ac43",
          "sha256": "77dc7e5a5a33d5b7d4c6f77cd6160b34b0b02223f85ccd42e27383c4c1bec7f5",
          "sha1": "bdaa0fea6fb748a0f7d02e45e4378e6a3974d238",
          "md5": "bb13f88116f0e068ae8cd78323a41eab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "laser_assembler-1.7.8-sources.jar",
          "url": "laser_assembler-1.7.8-sources.jar",
          "size": 3107,
          "sha512": "7c37a461b626393cccba030602bbfbc778d0a9c313e567c40e3c063e37f6880ed5352761fbb1a5435d408c57982a2a3fdafc87da492d917c48e3662cba68ef00",
          "sha256": "a72c8b51d36b3af5602d372b7c9d0c675ba37ea28aee26d64be7dd477330c958",
          "sha1": "b9142b4f317dbb175f8bef3b8f663bb1cd5841c7",
          "md5": "8e3b8763928cbe57719c21a9563b282a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "laser_assembler-1.7.8-javadoc.jar",
          "url": "laser_assembler-1.7.8-javadoc.jar",
          "size": 96362,
          "sha512": "cff6d2629da73209eca62d988b2e6e1042b2c1162a9c6b34fe38fdf80047788b4c124cd99633b64538af0f5e52c5c5769b969ab783394228313588d8d094a732",
          "sha256": "2e6f77b1428e6408e8c0c49d064a13ab0a7e9bb4e8888c782bf50b2268418266",
          "sha1": "8a694521a9edcfca26bce3bb7e6d6a1e81b7d932",
          "md5": "bb8d57e5f1249cd3d34b34ade3fe99ee"
        }
      ]
    }
  ]
}
