{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "geometry_msgs",
    "version": "1.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        }
      ],
      "files": [
        {
          "name": "geometry_msgs-1.13.0.jar",
          "url": "geometry_msgs-1.13.0.jar",
          "size": 15698,
          "sha512": "91c6c4690651e41840c86c5a49b8d4ed195ce02043451488e0e05587783c55fbb8133068d4ea62fa40c4781f222ce9ce2b6b08a01155b8eebad87484dc1da876",
          "sha256": "5384ff8c21ef045544d630b25cf41942888e61d5e4a6a2a693d2e83c214034fd",
          "sha1": "97137c2c67917d9ce3e91729e3c2b33bbe9189ea",
          "md5": "efd3017a5fc0879915b390f54d3aeb7a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        }
      ],
      "files": [
        {
          "name": "geometry_msgs-1.13.0.jar",
          "url": "geometry_msgs-1.13.0.jar",
          "size": 15698,
          "sha512": "91c6c4690651e41840c86c5a49b8d4ed195ce02043451488e0e05587783c55fbb8133068d4ea62fa40c4781f222ce9ce2b6b08a01155b8eebad87484dc1da876",
          "sha256": "5384ff8c21ef045544d630b25cf41942888e61d5e4a6a2a693d2e83c214034fd",
          "sha1": "97137c2c67917d9ce3e91729e3c2b33bbe9189ea",
          "md5": "efd3017a5fc0879915b390f54d3aeb7a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "geometry_msgs-1.13.0-sources.jar",
          "url": "geometry_msgs-1.13.0-sources.jar",
          "size": 12943,
          "sha512": "af74f078b8b8786f074840e8a8593be8c4243b5289e24e1954c3931666235f88ee4b07432b8e6c0f114e57880640219cd04cd609cd229bce44d715a4e69fae9d",
          "sha256": "75eb83913ba8bdb3ffb13ec137b49d267c30f1f3895b1c9a51a86afe89e941ac",
          "sha1": "dfc6f24a0395fddce7a1e7a043f07d91e6fa5aa8",
          "md5": "a2b7953ed06efcf33bcd35cd8cabeebe"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "geometry_msgs-1.13.0-javadoc.jar",
          "url": "geometry_msgs-1.13.0-javadoc.jar",
          "size": 162552,
          "sha512": "339426e24fb4b549d9de8623db77a7a11360fd0ce2d3abc866cd8a294a30d68d474637a8bd00412ecfe821eae1946590b9b6762cb600dfd8884741c1174173bc",
          "sha256": "faa7d143827ca084761da3ee76c1fb73bc67614efffe826e6eebf785d31cb3e5",
          "sha1": "591e24cb81ded81c4e3a0b88005f70df1bbdd6c3",
          "md5": "7055ef7365b598460d37b97426eeaa9f"
        }
      ]
    }
  ]
}
