{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "controller_manager_msgs",
    "version": "0.19.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        }
      ],
      "files": [
        {
          "name": "controller_manager_msgs-0.19.4.jar",
          "url": "controller_manager_msgs-0.19.4.jar",
          "size": 13201,
          "sha512": "dd5184a3aacd378b44c9524fd6f84517de349be30edeb84f1026243f9a5f993621e1d00c2e7552fb25d8408cbc4977107f8807f5a9018833bb42673d52b40f0e",
          "sha256": "83f282a08a483025bc411dda61105ab4d2895bfe9cce3976ce3dec7b2922b1a2",
          "sha1": "5ba32cd7ffdd92ec5bda273ed00e205b76fa57d9",
          "md5": "f18788a88b78fd982a6d609550ac2592"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        }
      ],
      "files": [
        {
          "name": "controller_manager_msgs-0.19.4.jar",
          "url": "controller_manager_msgs-0.19.4.jar",
          "size": 13201,
          "sha512": "dd5184a3aacd378b44c9524fd6f84517de349be30edeb84f1026243f9a5f993621e1d00c2e7552fb25d8408cbc4977107f8807f5a9018833bb42673d52b40f0e",
          "sha256": "83f282a08a483025bc411dda61105ab4d2895bfe9cce3976ce3dec7b2922b1a2",
          "sha1": "5ba32cd7ffdd92ec5bda273ed00e205b76fa57d9",
          "md5": "f18788a88b78fd982a6d609550ac2592"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "controller_manager_msgs-0.19.4-sources.jar",
          "url": "controller_manager_msgs-0.19.4-sources.jar",
          "size": 11217,
          "sha512": "0bc19faafb3b44b513607cc0da4b95431edfe19f154166294cd5cf78f67ce87fca45ab50333191713487d270368bd1d955dd6551c3b7f2e10be6111dffead540",
          "sha256": "5835179a8f7815a17613952569a311ac47dd67e52ba1ce032ad068e5b722a416",
          "sha1": "4de3842f35c30407908a57d99df3b7a1e6e020df",
          "md5": "119c01df8adbff06267d40939b831ada"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "controller_manager_msgs-0.19.4-javadoc.jar",
          "url": "controller_manager_msgs-0.19.4-javadoc.jar",
          "size": 140200,
          "sha512": "f8a806f16dddae862b50a767457e3a00eef12cfa836c9129dccd5f9064a61a2260c3c9db439b5f412cbd0d7460e89001a3c4ade87216fe3623ed2a0af5a3f9fd",
          "sha256": "ab09b5e52006343c51e5f51fb6f8d071c787a4c51e1c0b5f12e58da92eb6ffab",
          "sha1": "eb93e8015c1dfdf8e6957197b979fd6bc6e08901",
          "md5": "83b9413de396543d46d578cfbe78fbfd"
        }
      ]
    }
  ]
}
