{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "rospy_tutorials",
    "version": "0.10.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        }
      ],
      "files": [
        {
          "name": "rospy_tutorials-0.10.2.jar",
          "url": "rospy_tutorials-0.10.2.jar",
          "size": 3676,
          "sha512": "bf194af4c125ff089b9d3c9cf37484ca25870ae5eb92ea4bb4c1147036c4021e0ba783ff3a9a16ce9d04fb0e718009909a0277a558fdddf93817b548b9a6df8a",
          "sha256": "d51e58d86366b33d969ec7bea1a0581d6c522f69cc534d09f22ea9b228b1636f",
          "sha1": "33eb283e968f63dcc339f0939c6dab31838a3659",
          "md5": "66f7e83fa2f48dcea21680c816b31fc5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        }
      ],
      "files": [
        {
          "name": "rospy_tutorials-0.10.2.jar",
          "url": "rospy_tutorials-0.10.2.jar",
          "size": 3676,
          "sha512": "bf194af4c125ff089b9d3c9cf37484ca25870ae5eb92ea4bb4c1147036c4021e0ba783ff3a9a16ce9d04fb0e718009909a0277a558fdddf93817b548b9a6df8a",
          "sha256": "d51e58d86366b33d969ec7bea1a0581d6c522f69cc534d09f22ea9b228b1636f",
          "sha1": "33eb283e968f63dcc339f0939c6dab31838a3659",
          "md5": "66f7e83fa2f48dcea21680c816b31fc5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rospy_tutorials-0.10.2-sources.jar",
          "url": "rospy_tutorials-0.10.2-sources.jar",
          "size": 3110,
          "sha512": "1d74849d1102b4d91dd1d8905e7a57a21e9643b0d380b64d8fecfd6a25678d2af25ea61afac4f12ba41260942d28dcdc1834c02e98ec9f32489e4f5ef19b07b1",
          "sha256": "087f8f975f07107e7711ac9256b9d80c18dd683550fd0ead0ca43aef81b33ab1",
          "sha1": "d469fd08f95a422686be64d6827b8c34efd93860",
          "md5": "62e9b76988d51cf0b0937576431930a2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rospy_tutorials-0.10.2-javadoc.jar",
          "url": "rospy_tutorials-0.10.2-javadoc.jar",
          "size": 101606,
          "sha512": "1630e2c2f930db043ab8c11e356aa1c1fdb801c0e6fdb8a1891cf112870d85e5d5424804d09c4cf2ca3fe40161039c16b85b962874d8d081e348ce42992b9654",
          "sha256": "fe236fa44f913b7c677f298d3b3ea8a5030ca07ef169341c33676a93ae9f4b87",
          "sha1": "017819fdde41b7526c90624a06b98c2b425b4a11",
          "md5": "58d5f6cf79ac948a65655f38ef8e5be3"
        }
      ]
    }
  ]
}
