{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "smach_msgs",
    "version": "2.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        }
      ],
      "files": [
        {
          "name": "smach_msgs-2.5.0.jar",
          "url": "smach_msgs-2.5.0.jar",
          "size": 2488,
          "sha512": "28c0a6059b028db8c9c61119ad8c9169e679f88817c64ed1c9f2d835be14221399da4c046325674e19a53fc6cc4c1a926dd5702c3aa996e3bb9fd2997a38af28",
          "sha256": "108d26a68a5e5d98dc2af394b9bcdbd65a00c0216d1d884f4fcf84cf889f1120",
          "sha1": "bd8960b6b695c637e9a42064f1a14dfc2d55ace5",
          "md5": "7da31daba2f150b12851f2e9307a6414"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        }
      ],
      "files": [
        {
          "name": "smach_msgs-2.5.0.jar",
          "url": "smach_msgs-2.5.0.jar",
          "size": 2488,
          "sha512": "28c0a6059b028db8c9c61119ad8c9169e679f88817c64ed1c9f2d835be14221399da4c046325674e19a53fc6cc4c1a926dd5702c3aa996e3bb9fd2997a38af28",
          "sha256": "108d26a68a5e5d98dc2af394b9bcdbd65a00c0216d1d884f4fcf84cf889f1120",
          "sha1": "bd8960b6b695c637e9a42064f1a14dfc2d55ace5",
          "md5": "7da31daba2f150b12851f2e9307a6414"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "smach_msgs-2.5.0-sources.jar",
          "url": "smach_msgs-2.5.0-sources.jar",
          "size": 2034,
          "sha512": "4ad1a0025210c432d4f1037933416ba194bbef72b3f25a27be24f43dc52b6ce2fa94c3a8ee467c996fe41c2ea100a9ae41026c2ed11a21152ca3cee1bc364bfe",
          "sha256": "37e0fa2bd10bbb5b2cbc92a5c4e6e3702dded3c8feef6e5de72dfbefc3996b95",
          "sha1": "d83fc6e5a88e7f34818e37c676cd47a03a0c6ecd",
          "md5": "d73ec52ba55bdf4204e7f000a1d0084a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "smach_msgs-2.5.0-javadoc.jar",
          "url": "smach_msgs-2.5.0-javadoc.jar",
          "size": 91254,
          "sha512": "90fa388ab8667de96ee38e6bbca0153fad1c21cf7463464c3d4393aae19dee5d7330034f0d2515d5da6ed7b8b339fb1dd6cb3415624c3f8c64afcaa39bb47b8a",
          "sha256": "15c4018c9339099989c32db61e9fa58ab99bfc08becc47c7404cb595d799ae9d",
          "sha1": "0187918e902eb7c8c94e6f26d2624c0fa12758ad",
          "md5": "8a0994f83a3bd8a7ba911b575f5e9130"
        }
      ]
    }
  ]
}
