{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "diagnostic_msgs",
    "version": "1.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        }
      ],
      "files": [
        {
          "name": "diagnostic_msgs-1.13.0.jar",
          "url": "diagnostic_msgs-1.13.0.jar",
          "size": 6067,
          "sha512": "b2409a0baccec01a457ef42f5a8e162bf5e9fd978478b3c3d730d8912052d40af9e2ef7112278b588aa327e292238df20be10ec6b5fe3baca4ec4ea27a4f3c2f",
          "sha256": "5d7a04393e5c50d0d4ab7f31883904e29efd5c6832367da8422d3d1ab65a4540",
          "sha1": "711b721b4aa269c3b37d968f94ca7c1bd9b14dcb",
          "md5": "422d42a39088acef2a1644884a8be95f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        }
      ],
      "files": [
        {
          "name": "diagnostic_msgs-1.13.0.jar",
          "url": "diagnostic_msgs-1.13.0.jar",
          "size": 6067,
          "sha512": "b2409a0baccec01a457ef42f5a8e162bf5e9fd978478b3c3d730d8912052d40af9e2ef7112278b588aa327e292238df20be10ec6b5fe3baca4ec4ea27a4f3c2f",
          "sha256": "5d7a04393e5c50d0d4ab7f31883904e29efd5c6832367da8422d3d1ab65a4540",
          "sha1": "711b721b4aa269c3b37d968f94ca7c1bd9b14dcb",
          "md5": "422d42a39088acef2a1644884a8be95f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "diagnostic_msgs-1.13.0-sources.jar",
          "url": "diagnostic_msgs-1.13.0-sources.jar",
          "size": 5155,
          "sha512": "340b094f3ec4c8f7fe66cec144bb588b297960601eeff6e50505e0293bccfd263430f0f90bb97ad0e61b918cfdd7dd2786f3c729cd114d6efaf4af49afc6d71e",
          "sha256": "c2382433d3cd59af2b604a418716fb043875bd793cfcf626e8c0b41156a2f92b",
          "sha1": "1c9744ea8b5ead281162bb725b915a1f7b34f00d",
          "md5": "c3c542ddcbe530758d471cf3b12fcf14"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "diagnostic_msgs-1.13.0-javadoc.jar",
          "url": "diagnostic_msgs-1.13.0-javadoc.jar",
          "size": 106116,
          "sha512": "7f33c4d47225448b03991614216f253a9d0035be16aa5e4b70cfa4dab6de35598544fa090020f3a66b1870883296b2f61874c3dbd0f0117d97a026fcadfddcdc",
          "sha256": "ed3cabb399a1c6c5c55589d371cb65a5e27701296570f590858d1bb5f6ceea7e",
          "sha1": "f53f4e81cd2cdcc490c213f5f874a5ae24598882",
          "md5": "38a1be0fcbd2bd74ad5fca240bd709b6"
        }
      ]
    }
  ]
}
