{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "control_msgs",
    "version": "1.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "actionlib_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "trajectory_msgs",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "control_msgs-1.5.2.jar",
          "url": "control_msgs-1.5.2.jar",
          "size": 29564,
          "sha512": "b59fe6df24f0483bdf0031fa56472363de6ddc91b5fead298f3d68adb6775157e585baec41177db97ebb5576b9b1c1eaef7276190b04b27e96a052ec41677b28",
          "sha256": "c00184e6a7a410e82f260aff460ff90fac8b22b4e0b3f2980fdac08f1477d5e2",
          "sha1": "c7e02bb2b039b010a09b40369ecd2faea4a6372a",
          "md5": "19e32c7ff3072f2df73269d1cfbb0b88"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "actionlib_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "trajectory_msgs",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "control_msgs-1.5.2.jar",
          "url": "control_msgs-1.5.2.jar",
          "size": 29564,
          "sha512": "b59fe6df24f0483bdf0031fa56472363de6ddc91b5fead298f3d68adb6775157e585baec41177db97ebb5576b9b1c1eaef7276190b04b27e96a052ec41677b28",
          "sha256": "c00184e6a7a410e82f260aff460ff90fac8b22b4e0b3f2980fdac08f1477d5e2",
          "sha1": "c7e02bb2b039b010a09b40369ecd2faea4a6372a",
          "md5": "19e32c7ff3072f2df73269d1cfbb0b88"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "control_msgs-1.5.2-sources.jar",
          "url": "control_msgs-1.5.2-sources.jar",
          "size": 24456,
          "sha512": "cebfd53e1d86fc001b825a1ca42bbea34af47c73a4e154c966e20daeabb1109bc7163b63a36dbca79330760308dd3fb9191b5a4a96669c4386a3352253bacd72",
          "sha256": "e973433a04850fa03cc1a199fe0ef4895a8f4e3a7e0a70bcd8085590079535bc",
          "sha1": "765025b0e9e5ef2f318cc876f9854eaf5836446f",
          "md5": "2a50baf636457d2af6013c8d70be8a00"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "control_msgs-1.5.2-javadoc.jar",
          "url": "control_msgs-1.5.2-javadoc.jar",
          "size": 221430,
          "sha512": "db8446961b1e2a8ffbb18b79b36139df9e74416edfba0d82fe6c5ef2be895de860c8ce94a859a73ffd9eca6e77bdd18f4326171af2f2380bc69c7d04f46008ab",
          "sha256": "4b48887f4ff7d35255726f1074ea9144b03678f042902529194c88edee3dc2dd",
          "sha1": "6cdf2312b1b926d8c7d87873b1206c49d3bab6dd",
          "md5": "c7f9c774ddfd54edb418f6f35e9f18b2"
        }
      ]
    }
  ]
}
