{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "actionlib_tutorials",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "actionlib",
          "version": {
            "requires": "1.13.2"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "actionlib_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        }
      ],
      "files": [
        {
          "name": "actionlib_tutorials-0.2.0.jar",
          "url": "actionlib_tutorials-0.2.0.jar",
          "size": 8752,
          "sha512": "5eafbc6cf427f53ec6f47d02dab66f33a6b994fdb512604c0596d38b88def6fa4af92750239eed2c774507240e295de4929c7523896da4a7f95ebc3c577f0cff",
          "sha256": "387e8afb192cfd88658d4b49156f046b07231bce6165e7f86855899d4d1b2425",
          "sha1": "fbe3b25e392489bb60df428a6dad0c20f693120a",
          "md5": "9d8bd9cd06ff8d316096952dc283662b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "actionlib",
          "version": {
            "requires": "1.13.2"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "actionlib_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        }
      ],
      "files": [
        {
          "name": "actionlib_tutorials-0.2.0.jar",
          "url": "actionlib_tutorials-0.2.0.jar",
          "size": 8752,
          "sha512": "5eafbc6cf427f53ec6f47d02dab66f33a6b994fdb512604c0596d38b88def6fa4af92750239eed2c774507240e295de4929c7523896da4a7f95ebc3c577f0cff",
          "sha256": "387e8afb192cfd88658d4b49156f046b07231bce6165e7f86855899d4d1b2425",
          "sha1": "fbe3b25e392489bb60df428a6dad0c20f693120a",
          "md5": "9d8bd9cd06ff8d316096952dc283662b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "actionlib_tutorials-0.2.0-sources.jar",
          "url": "actionlib_tutorials-0.2.0-sources.jar",
          "size": 7305,
          "sha512": "7bcb75968299c742c28663ee64b0164342d5b3de48aac492b4bd5790cd3de50841fdf1ee6daab58a622110975253dc5718d661014b299be30cbe7db6a8396a64",
          "sha256": "636aef123c693ce72ed182fee7fe032e67386c228dcead82d3e229a7be299861",
          "sha1": "f46531c3662f27639aeec6c28f925039ffcbd34b",
          "md5": "7d2af0219894925e8235f6fe3f3dfbb2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "actionlib_tutorials-0.2.0-javadoc.jar",
          "url": "actionlib_tutorials-0.2.0-javadoc.jar",
          "size": 124974,
          "sha512": "57722939572d9bf5b31b2203750c00f1bf103649f062b7452640cee423908cbafda677946747f5a57c2465908a484c6ed320a68d2e50f037c7bab1105938eb4b",
          "sha256": "bdac97657ce407ee0f03ecbc1e33ab542bd873420f3a508983f9a975bf9dcf39",
          "sha1": "fb9486571f62fc487d5a99f22de54ec22218c042",
          "md5": "52d9343bb3d5b48ba1d0bf98f530de61"
        }
      ]
    }
  ]
}
