{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.rosjava",
    "module": "rosjava_actionlib",
    "version": "2026.03.29.02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "actionlib_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "actionlib",
          "version": {
            "requires": "1.13.2"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        }
      ],
      "files": [
        {
          "name": "rosjava_actionlib-2026.03.29.02.jar",
          "url": "rosjava_actionlib-2026.03.29.02.jar",
          "size": 69132,
          "sha512": "82a77d22d8665283a0a398f75997f28af09538cac008e8a36e59d6abe86ed736a8019c7b8bb87950270cb7cbbddf774c95114e3ef353d7197daa820278d15cd3",
          "sha256": "7a47155d2aeb5920f0f7153b083001934f0aae456f510395f6fad3125ad90688",
          "sha1": "83e1e987d44b9ad85ba2ddba2292d06c42f2a4e6",
          "md5": "29710fa857a7733e3fb00ca5b1e0b55e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_bootstrap",
          "module": "message_generation",
          "version": {
            "requires": "0.3.8"
          }
        },
        {
          "group": "org.ros.rosjava_core",
          "module": "rosjava",
          "version": {
            "requires": "0.4.1.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.0.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.18.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-configuration2",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "actionlib_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "actionlib",
          "version": {
            "requires": "1.13.2"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-slf4j-impl",
          "version": {
            "requires": "2.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "rosjava_actionlib-2026.03.29.02.jar",
          "url": "rosjava_actionlib-2026.03.29.02.jar",
          "size": 69132,
          "sha512": "82a77d22d8665283a0a398f75997f28af09538cac008e8a36e59d6abe86ed736a8019c7b8bb87950270cb7cbbddf774c95114e3ef353d7197daa820278d15cd3",
          "sha256": "7a47155d2aeb5920f0f7153b083001934f0aae456f510395f6fad3125ad90688",
          "sha1": "83e1e987d44b9ad85ba2ddba2292d06c42f2a4e6",
          "md5": "29710fa857a7733e3fb00ca5b1e0b55e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosjava_actionlib-2026.03.29.02-sources.jar",
          "url": "rosjava_actionlib-2026.03.29.02-sources.jar",
          "size": 44421,
          "sha512": "d3bdbf84466a6acab404473c987fa89dcc578fa4ce10763cc14102a3d169d77e4ae8a1faef30704187770f29faccfc3099e973d542ebd20a5c2b9d6dafdc905c",
          "sha256": "6e82cb078163e3fff2ef3deec60da1cb7dd5b5e896e189d1582f995978331541",
          "sha1": "9a9329385bfcff19e658f95683454eefdf338fab",
          "md5": "993d33ea53436a5981e0bc4e6a3a1437"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosjava_actionlib-2026.03.29.02-javadoc.jar",
          "url": "rosjava_actionlib-2026.03.29.02-javadoc.jar",
          "size": 136185,
          "sha512": "391a72af4864815d0bd88b75d0d3eb5246a351a1aadce64b1d61bdd11eec94fc4325336bd0784e2a49b9e74329e3ad0831ea6e602aab41c4e92fe08526ca42c9",
          "sha256": "9b491d52d8e4c5bc9ad1e792eeb92ae055a5862e2067b7b1c23dc06516e40101",
          "sha1": "26fda567ac8415100aad0f405ff1178c4a0f8af1",
          "md5": "0a3ad05fef511facdd870f49e2e2fa7f"
        }
      ]
    }
  ]
}
