{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "dynamic_reconfigure",
    "version": "1.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        }
      ],
      "files": [
        {
          "name": "dynamic_reconfigure-1.7.1.jar",
          "url": "dynamic_reconfigure-1.7.1.jar",
          "size": 6696,
          "sha512": "c1284d76bf9c12f7cc4a2b35e1e973859d6e3d2f49a5d64eb45607edfbcbae2093ee706619cad1efba056aef95ff374fb29c0def47a1f565ee83fb67ac05293b",
          "sha256": "e78a3002b36cf74625b04b16d448c3c3cce55172f5e1f70b45d5617539af15d3",
          "sha1": "7c3f65102cc72cbe2a3459b6baa57a55f032eb28",
          "md5": "1af11d88fe0a7b60b0195ab307e2eb21"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        }
      ],
      "files": [
        {
          "name": "dynamic_reconfigure-1.7.1.jar",
          "url": "dynamic_reconfigure-1.7.1.jar",
          "size": 6696,
          "sha512": "c1284d76bf9c12f7cc4a2b35e1e973859d6e3d2f49a5d64eb45607edfbcbae2093ee706619cad1efba056aef95ff374fb29c0def47a1f565ee83fb67ac05293b",
          "sha256": "e78a3002b36cf74625b04b16d448c3c3cce55172f5e1f70b45d5617539af15d3",
          "sha1": "7c3f65102cc72cbe2a3459b6baa57a55f032eb28",
          "md5": "1af11d88fe0a7b60b0195ab307e2eb21"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dynamic_reconfigure-1.7.1-sources.jar",
          "url": "dynamic_reconfigure-1.7.1-sources.jar",
          "size": 5384,
          "sha512": "359a74c1ea6434ae22a34f1a2c0758b4aa5b431a0868fec43dac8d7a6f552b5a27aaf33f6ed83398c6ce67faac1ddb6db771d85ead9c8ded74557306ee30850c",
          "sha256": "43fd5486e9c7ceea25e752f478256408e927a9fed36a8212cefbbc0cf6baed5e",
          "sha1": "640cce2abe468ce025ffae999f89fe3392fbff53",
          "md5": "6ab01c4dd0bf107dbfe641ab28e19a1e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dynamic_reconfigure-1.7.1-javadoc.jar",
          "url": "dynamic_reconfigure-1.7.1-javadoc.jar",
          "size": 117879,
          "sha512": "40486898f8f31dd02738805c2301d239cf8be17f50890d62d174d4388e43bd455b03dc01d272693c438bc689179c2fdaf1c1fd6e3f06a7ba81aa3099bfa3dce3",
          "sha256": "2cb0ec2d0d499da78371059eff08302d3796d9688fe09a5100ed4f5f90b9a7d8",
          "sha1": "e9cfec70b9eea708e8f0e30769fd930d86cded19",
          "md5": "fe26cae01e4c2f9b9221d47bc6e2ddbf"
        }
      ]
    }
  ]
}
