{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "std_msgs",
    "version": "0.5.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "std_msgs-0.5.13.jar",
          "url": "std_msgs-0.5.13.jar",
          "size": 14770,
          "sha512": "c5c42dc2190868a325248a28eba952dd5d7f4eed5bbbd5709b9fad24fb5013d357d2bb8ccfaa50683aab5afe83d43826193dd58c724fdefbd908986b9b2b22a3",
          "sha256": "a07505f55a5fe02c2728508ffe9a1f86ebd93376b9e49600f4362520f7e7f531",
          "sha1": "1ac882e2ff01aad1eb4bc35ec915335dae1ee585",
          "md5": "62943d2d2baae61e0b2ce89e78f133c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "std_msgs-0.5.13.jar",
          "url": "std_msgs-0.5.13.jar",
          "size": 14770,
          "sha512": "c5c42dc2190868a325248a28eba952dd5d7f4eed5bbbd5709b9fad24fb5013d357d2bb8ccfaa50683aab5afe83d43826193dd58c724fdefbd908986b9b2b22a3",
          "sha256": "a07505f55a5fe02c2728508ffe9a1f86ebd93376b9e49600f4362520f7e7f531",
          "sha1": "1ac882e2ff01aad1eb4bc35ec915335dae1ee585",
          "md5": "62943d2d2baae61e0b2ce89e78f133c8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "std_msgs-0.5.13-sources.jar",
          "url": "std_msgs-0.5.13-sources.jar",
          "size": 12082,
          "sha512": "66867cbaf89602f560164abf512052eca05ef8ef4e701503392b9e7b42efcb093c00db07e7081f91d843d5ec02bcb3fbd47033b2f2fde4a1463c1b96fea8d42c",
          "sha256": "6a09bcc93b4d21282879a3ba135348f1f6a998f58d50ca5d5342519fc97074e9",
          "sha1": "0ef50b7e358244545ac9b291157abf6a1fea0b7f",
          "md5": "509fc8a4456c07d0adbc0f23f5401b53"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "std_msgs-0.5.13-javadoc.jar",
          "url": "std_msgs-0.5.13-javadoc.jar",
          "size": 165798,
          "sha512": "8ce4fedd1d5612a1a0df1fac033ebdb4f4ae5d8d8b33e0cae5c038d5be7b04329e672bbf2cbd01691733bb96c10309cd8049bb062cc4a629613516e3dbf12d32",
          "sha256": "005bb3dc885c9c28eecea54525c315686e17d9ec54a8807affc3c14609cdc999",
          "sha1": "5505cd0666d17f4d7e3493fa72ba7e816082065e",
          "md5": "1c05d08142fe4ae9453097df4d66d695"
        }
      ]
    }
  ]
}
