{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_core",
    "module": "rosjava_geometry",
    "version": "0.3.9.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosjava_geometry-0.3.9.4.jar",
          "url": "rosjava_geometry-0.3.9.4.jar",
          "size": 14947,
          "sha512": "3bc47796d2662d5d2b312e6215204c44b92464c9556ad4730bec0f85059bfb86a7bcf31eccb9c91c0d0063b7c898677eeaa80fcfb8914f2402117cc4abd6b9e8",
          "sha256": "4f82510ebc9991209a0245b5b8ae10aa10744f91e5a6cf6ebb107f979575995d",
          "sha1": "8bc46b0d515714da2fda9595d9251e2e20c9df22",
          "md5": "62b963e0e6e783311e88912805bfbd59"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.0.0-jre"
          }
        },
        {
          "group": "org.ros.rosjava_core",
          "module": "rosjava",
          "version": {
            "requires": "0.3.9.4"
          }
        }
      ],
      "files": [
        {
          "name": "rosjava_geometry-0.3.9.4.jar",
          "url": "rosjava_geometry-0.3.9.4.jar",
          "size": 14947,
          "sha512": "3bc47796d2662d5d2b312e6215204c44b92464c9556ad4730bec0f85059bfb86a7bcf31eccb9c91c0d0063b7c898677eeaa80fcfb8914f2402117cc4abd6b9e8",
          "sha256": "4f82510ebc9991209a0245b5b8ae10aa10744f91e5a6cf6ebb107f979575995d",
          "sha1": "8bc46b0d515714da2fda9595d9251e2e20c9df22",
          "md5": "62b963e0e6e783311e88912805bfbd59"
        }
      ]
    }
  ]
}
