{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "visualization_msgs",
    "version": "1.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        }
      ],
      "files": [
        {
          "name": "visualization_msgs-1.13.0.jar",
          "url": "visualization_msgs-1.13.0.jar",
          "size": 12077,
          "sha512": "848a4c3419f0fa5eeccd9af8b4cf9d90810b3b4ad80b582fe3142d2b0b34deee2c3fbe00e2e1d9cfde766e6b78ce9162abd2a67510f8c28503fe1c057c311ba3",
          "sha256": "e5b7c1e94a91d12d5e3aeabfbc9009797e3ec5b262216f92c6d022bdb091be7a",
          "sha1": "6483a959e3abf2e4b6847427000485e57efbdfb9",
          "md5": "66cd60808b6abffa76d9e109e8c31a3f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        }
      ],
      "files": [
        {
          "name": "visualization_msgs-1.13.0.jar",
          "url": "visualization_msgs-1.13.0.jar",
          "size": 12077,
          "sha512": "848a4c3419f0fa5eeccd9af8b4cf9d90810b3b4ad80b582fe3142d2b0b34deee2c3fbe00e2e1d9cfde766e6b78ce9162abd2a67510f8c28503fe1c057c311ba3",
          "sha256": "e5b7c1e94a91d12d5e3aeabfbc9009797e3ec5b262216f92c6d022bdb091be7a",
          "sha1": "6483a959e3abf2e4b6847427000485e57efbdfb9",
          "md5": "66cd60808b6abffa76d9e109e8c31a3f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "visualization_msgs-1.13.0-sources.jar",
          "url": "visualization_msgs-1.13.0-sources.jar",
          "size": 10001,
          "sha512": "6eb9378be74dbfd127d297aebef6fb1e529567a16dbb05de31c30e5f304eb804c5112a606159716bb64ea1283c7f0b4d7bdbb779adb61eba175a7c938b14be07",
          "sha256": "ca55708087d0e4724f2570fc0ef0bcab3e19bfc13820333903a0c6da93ba8866",
          "sha1": "a144feb2e2588f08a27481e12423d3c6cb886cc1",
          "md5": "4a65d5af9ff1f80a7c89fac8daba8e4e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "visualization_msgs-1.13.0-javadoc.jar",
          "url": "visualization_msgs-1.13.0-javadoc.jar",
          "size": 123326,
          "sha512": "2b2597c8a70b3ba8d55a7bf973de9c7888366aaae08cf2b772391e5309671cb7acee9cc55e233ff68d41c94e2f8b69b4da97014b44da2daeca752bd9c687dcbe",
          "sha256": "53103ec3414a2fd0cb9ff8bc804bcbc106b6b061a974645cd639ffe22559db6f",
          "sha1": "f557c79c509470531fea9360eda415ec0d18fdc9",
          "md5": "ff26f9ab0c75325b179b4e2a8cdde60a"
        }
      ]
    }
  ]
}
