{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "pcl_msgs",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "sensor_msgs",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "pcl_msgs-0.3.0.jar",
          "url": "pcl_msgs-0.3.0.jar",
          "size": 3365,
          "sha512": "7edf7341fde76bebeb09b75550d78aae6ed84d1e858439b11c96182494a937cffb2c8c18aa841cfefdb83fd23e4c64699f31b54b1bc166ac55f1f17f7739a972",
          "sha256": "c50c53ade3d30e9c245eb707c373d77488ed35d212a2b827298a1641dd299acb",
          "sha1": "33635037031929d46edb904b732af77629f78215",
          "md5": "46c9d6f56a170ffb18eb4c418b1a4da8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "sensor_msgs",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "pcl_msgs-0.3.0.jar",
          "url": "pcl_msgs-0.3.0.jar",
          "size": 3365,
          "sha512": "7edf7341fde76bebeb09b75550d78aae6ed84d1e858439b11c96182494a937cffb2c8c18aa841cfefdb83fd23e4c64699f31b54b1bc166ac55f1f17f7739a972",
          "sha256": "c50c53ade3d30e9c245eb707c373d77488ed35d212a2b827298a1641dd299acb",
          "sha1": "33635037031929d46edb904b732af77629f78215",
          "md5": "46c9d6f56a170ffb18eb4c418b1a4da8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pcl_msgs-0.3.0-sources.jar",
          "url": "pcl_msgs-0.3.0-sources.jar",
          "size": 2775,
          "sha512": "c37890177046421a9e4f03e33a8719833f424ff458586033cf43ff832a0d62df7e8f58d04dc153425d952e2f40bfb877acbc008ea113bdde9169933d4353603a",
          "sha256": "158c3e71290ff69f2bbeb2bd7bf69c3d2e6d8ef68dbc622b41a114ce4ededba2",
          "sha1": "200538819840a10f0bde3ecb79bb227e1f6446bf",
          "md5": "8d558ac99682849927205c4a4308b533"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pcl_msgs-0.3.0-javadoc.jar",
          "url": "pcl_msgs-0.3.0-javadoc.jar",
          "size": 99847,
          "sha512": "5077a84ff1dcdc191556b6176f5c0c8576ff61d98310a1fa217f82e1ff81f8e0a6f5f00126899b9ad103df3dbec33d2eaf89eec619e1a88681c3cf659bca556e",
          "sha256": "d1f105094b2cdc34a9cef8ea6956a7ec27a4f53eb85275afa436bfa80bfdb1f0",
          "sha1": "c20de98c1bbde1db888fad5e980e7bcc6366d7f2",
          "md5": "54793130e97cac9c985f8de9d9985665"
        }
      ]
    }
  ]
}
