{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "nodelet",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        }
      ],
      "files": [
        {
          "name": "nodelet-1.10.0.jar",
          "url": "nodelet-1.10.0.jar",
          "size": 3969,
          "sha512": "ac70c9fc882c672af5f51eb276bf597f21e73d5f3a9095609f474ae560800130b2394112b3640dc7550886cd88ad802d460332a41440c5bf7c6a22a3acdc1341",
          "sha256": "cf3e52b929333954e4e495fbeae16424a63c4ff9c393cf2d12698cc3c74cb815",
          "sha1": "9d9a82ece33f07c6002c1a98682283acf31d4dce",
          "md5": "b7669b3ff11603a13010127d32914a74"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        }
      ],
      "files": [
        {
          "name": "nodelet-1.10.0.jar",
          "url": "nodelet-1.10.0.jar",
          "size": 3969,
          "sha512": "ac70c9fc882c672af5f51eb276bf597f21e73d5f3a9095609f474ae560800130b2394112b3640dc7550886cd88ad802d460332a41440c5bf7c6a22a3acdc1341",
          "sha256": "cf3e52b929333954e4e495fbeae16424a63c4ff9c393cf2d12698cc3c74cb815",
          "sha1": "9d9a82ece33f07c6002c1a98682283acf31d4dce",
          "md5": "b7669b3ff11603a13010127d32914a74"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nodelet-1.10.0-sources.jar",
          "url": "nodelet-1.10.0-sources.jar",
          "size": 3292,
          "sha512": "1e5833ee84f6402cb05e05c510b8161447d3af7f62342afe9c1a02265267a1ceb6ccd0723b31fbef454e59c4f59fd9085902793076b2bbe1ca22ad7d90687379",
          "sha256": "5040436964721eae92df0d6b5b412d941380844cd98ea46d58223e7b4fdeae25",
          "sha1": "601ac7b890b2908f6b62952258d4d677ab5ab00b",
          "md5": "329b478285ab337704ff422125c97007"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nodelet-1.10.0-javadoc.jar",
          "url": "nodelet-1.10.0-javadoc.jar",
          "size": 103204,
          "sha512": "1a2b3a57a5b3effd7508d4e47bd89ba0ad3a70028a7079da6782685e6122e49fab6f9b8ffac03e01199b9b9bbeba89a860422436e86a6ef0a22d0a03a87e8d68",
          "sha256": "1afce2e2c6284a88830a0a8445be9698a82fee595701ebba7c20d8339193b17b",
          "sha1": "478bb599429cde97e8bcbd1aec536b84ba2668b6",
          "md5": "35fdacc63a999c4efa861bbc2d06a546"
        }
      ]
    }
  ]
}
