{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "uuid_msgs",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        }
      ],
      "files": [
        {
          "name": "uuid_msgs-1.0.6.jar",
          "url": "uuid_msgs-1.0.6.jar",
          "size": 853,
          "sha512": "b3e1626e2cdcac9e7d45e56d07548d9d9d6f85fdd1eef330f8056a5f187fec37be9ee2c053c5cfddfbe144e24f1787c58df226ff27d8ae7adecd3186f7244eae",
          "sha256": "7b11e615209210ad374c45f67fccd0947f8c162713054dd8b23cf76e0c6efff0",
          "sha1": "a080c35dc99aeede7581b2439b492b678eadcc17",
          "md5": "3828b1ab2ce45fac7a64c7b345990f9f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        }
      ],
      "files": [
        {
          "name": "uuid_msgs-1.0.6.jar",
          "url": "uuid_msgs-1.0.6.jar",
          "size": 853,
          "sha512": "b3e1626e2cdcac9e7d45e56d07548d9d9d6f85fdd1eef330f8056a5f187fec37be9ee2c053c5cfddfbe144e24f1787c58df226ff27d8ae7adecd3186f7244eae",
          "sha256": "7b11e615209210ad374c45f67fccd0947f8c162713054dd8b23cf76e0c6efff0",
          "sha1": "a080c35dc99aeede7581b2439b492b678eadcc17",
          "md5": "3828b1ab2ce45fac7a64c7b345990f9f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "uuid_msgs-1.0.6-sources.jar",
          "url": "uuid_msgs-1.0.6-sources.jar",
          "size": 777,
          "sha512": "641e3d9602d3f7ec84518365c92ee0c9ff7b13cb4f6837a7bf073e977c92383ebea4650996eb44250b512ec4af510d88d8f0f731c9ba4f6f5e2ae4dd0df52cc0",
          "sha256": "9ab5ecd3e19e825c0b6e38a5ee50ea9ed372d3cb25d42bbf7c38585cc6f9d73d",
          "sha1": "3f7ba6e76bd3446de681e4277a1269330d6be19f",
          "md5": "21e68ed82606e23df77111376ea9e106"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "uuid_msgs-1.0.6-javadoc.jar",
          "url": "uuid_msgs-1.0.6-javadoc.jar",
          "size": 83848,
          "sha512": "b7cbd6c5ad39e43396baffbc91a13090a934e12f4365acf53bea4743708ad3837115d7d3e43885d209a8ef2f63d5db69d438aaad18e9405dc28f84a8a60feec7",
          "sha256": "31818b86eddbc702434f68b0381f51db98ad52ab2b5e4620679513fd69b06eb1",
          "sha1": "49b417404e424b40a224f29a8f38d34253c00807",
          "md5": "be8af54a1e287c46ae7c0f197023da56"
        }
      ]
    }
  ]
}
