{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "topic_tools",
    "version": "1.15.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        }
      ],
      "files": [
        {
          "name": "topic_tools-1.15.9.jar",
          "url": "topic_tools-1.15.9.jar",
          "size": 9382,
          "sha512": "510f61d24fdb0380bc1d15ed54d140e6e6cce0107061b48e98a3f680d5328e8490f1ffc2d2ea5fec86ffe163eecdd2d0a00a1fd71a30cf74cf6cc81c6c7534cc",
          "sha256": "b35ed7ec50b14e3704746b09da4b826b6840bbb532f1c49424903bf3bf7e33b2",
          "sha1": "910bb3c007dc1b9e8177e847e33f47ab876e0472",
          "md5": "ce8ea35f240b35bb2e49b6bd7180761d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        }
      ],
      "files": [
        {
          "name": "topic_tools-1.15.9.jar",
          "url": "topic_tools-1.15.9.jar",
          "size": 9382,
          "sha512": "510f61d24fdb0380bc1d15ed54d140e6e6cce0107061b48e98a3f680d5328e8490f1ffc2d2ea5fec86ffe163eecdd2d0a00a1fd71a30cf74cf6cc81c6c7534cc",
          "sha256": "b35ed7ec50b14e3704746b09da4b826b6840bbb532f1c49424903bf3bf7e33b2",
          "sha1": "910bb3c007dc1b9e8177e847e33f47ab876e0472",
          "md5": "ce8ea35f240b35bb2e49b6bd7180761d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "topic_tools-1.15.9-sources.jar",
          "url": "topic_tools-1.15.9-sources.jar",
          "size": 7708,
          "sha512": "cf5147dc94e99debadaee9019b714730e65dd65f62dced3a1b4b92800ea6d2ca22f5c04d9ddde3c685d893dcac8b330c76726da743ceacc7a86baba35d1d03dc",
          "sha256": "dc0442d83b52b36ae9858878ae121714770b0a2ea7155d027116072e09cede2e",
          "sha1": "5371638082b10f7b22060ef6e4911f1b50d52ba5",
          "md5": "2bb3ab91523f7d21fdcbb636350f8ee1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "topic_tools-1.15.9-javadoc.jar",
          "url": "topic_tools-1.15.9-javadoc.jar",
          "size": 136276,
          "sha512": "9885e7ef919600b9066672fb480fb07612465b05f6a690422ad2006bec5967c8c62e100d44f1130eacec0a66ca9a4aaede48ca3cf18622c06785854ec7b25760",
          "sha256": "4d0daaaba90a2cf2f2cfcdf6aa5750df5938b1f5a46eb145b8f1466574427ccb",
          "sha1": "fa10d31875970a69f073a424e357aaeb7046061c",
          "md5": "c458943edb5e61d43b1b030e62e6ddfa"
        }
      ]
    }
  ]
}
