{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "rosserial_mbed",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "rosserial_msgs",
          "version": {
            "requires": "0.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "rosserial_mbed-0.9.1.jar",
          "url": "rosserial_mbed-0.9.1.jar",
          "size": 1935,
          "sha512": "ac5a17874daeb387a675cd9a044bb806dcf64d88b4be3e019dfbfc77c8dc33255f812578472d80270de297d11c80b8ec3c6c440cb7d7b479899abd41e56e596c",
          "sha256": "4a710db188a79d2e58915a1ded3b29bbdbcc73da05258965f84f891bcf593c76",
          "sha1": "f75a44900d94fe948facccb33c35ec9f9cc3710e",
          "md5": "183736c31052dcc0db07b4f1377d3f8a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "rosserial_msgs",
          "version": {
            "requires": "0.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "rosserial_mbed-0.9.1.jar",
          "url": "rosserial_mbed-0.9.1.jar",
          "size": 1935,
          "sha512": "ac5a17874daeb387a675cd9a044bb806dcf64d88b4be3e019dfbfc77c8dc33255f812578472d80270de297d11c80b8ec3c6c440cb7d7b479899abd41e56e596c",
          "sha256": "4a710db188a79d2e58915a1ded3b29bbdbcc73da05258965f84f891bcf593c76",
          "sha1": "f75a44900d94fe948facccb33c35ec9f9cc3710e",
          "md5": "183736c31052dcc0db07b4f1377d3f8a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosserial_mbed-0.9.1-sources.jar",
          "url": "rosserial_mbed-0.9.1-sources.jar",
          "size": 1644,
          "sha512": "c3fd9d8368b4909c24b0c76eed9cd39ef935f53c10015b8cd8f8142ac18009ca7b740e585e067698f8f9ca6fbf8b16d956a5e6d0c96049247fa92cf4d77d82ca",
          "sha256": "da19818c69bbffe171ddc67bfab51e33f7bd87ab049999e76f6075fe20485ab8",
          "sha1": "cf8f99502dd2244270afef55ff51beb8427c2b9f",
          "md5": "2763966b37c30411251a6956cbb5c6ee"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosserial_mbed-0.9.1-javadoc.jar",
          "url": "rosserial_mbed-0.9.1-javadoc.jar",
          "size": 91516,
          "sha512": "a45db2eb5d79cbacf44b03d0e21bbbf27a9219809a20b9231bbf40813b57f4039726c6c0b61e78b8af8db7f08b2c005658396f58106e4c4c2f11a4453f2ee961",
          "sha256": "3f9afaec541e6ea51eab3cdc77bbb2bde65252d739be102bcc79338f2d176a25",
          "sha1": "e37719ad77a55817da82c647028a48041c1bb82e",
          "md5": "148bac7658cb5ad44a508a279f1a3c0e"
        }
      ]
    }
  ]
}
