{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "costmap_2d",
    "version": "1.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "nav_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "sensor_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "map_msgs",
          "version": {
            "requires": "1.14.1"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "dynamic_reconfigure",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "visualization_msgs",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "costmap_2d-1.17.1.jar",
          "url": "costmap_2d-1.17.1.jar",
          "size": 952,
          "sha512": "3ddee683f0b46bb747d52b9450e6cdbd8347336e7f41c3e337e53377afedfc187f290fd361834d6638d7ce5b1e87721c16265528c4dfb25f2d5beb031c73162b",
          "sha256": "c1967ff400b669be1c6c2a46fbcaf4363702b49e7fdb9cbf3965c19c85205c7e",
          "sha1": "8c2b72d53e5a08d9d0e360c98cf5cadc93c7c156",
          "md5": "136748f2c3f8059085ae555cc20f30ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "nav_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "sensor_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "map_msgs",
          "version": {
            "requires": "1.14.1"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "dynamic_reconfigure",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "visualization_msgs",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "costmap_2d-1.17.1.jar",
          "url": "costmap_2d-1.17.1.jar",
          "size": 952,
          "sha512": "3ddee683f0b46bb747d52b9450e6cdbd8347336e7f41c3e337e53377afedfc187f290fd361834d6638d7ce5b1e87721c16265528c4dfb25f2d5beb031c73162b",
          "sha256": "c1967ff400b669be1c6c2a46fbcaf4363702b49e7fdb9cbf3965c19c85205c7e",
          "sha1": "8c2b72d53e5a08d9d0e360c98cf5cadc93c7c156",
          "md5": "136748f2c3f8059085ae555cc20f30ad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "costmap_2d-1.17.1-sources.jar",
          "url": "costmap_2d-1.17.1-sources.jar",
          "size": 803,
          "sha512": "98ad7b12372f3f4a9b00a4e987ba08559f11f42b1258b4d7958b5e0a9575b5dcdfee9ae1ead0da928e0c80ff7dcb71acf4f4c13c7f9bd78464f16638ae8e1b17",
          "sha256": "63ddb324222bfc7bc32e6c12ff390bdad36449bf2d12150a57fb5478d919bff7",
          "sha1": "361e8a0e6614904ed01bcadf7c8baa2760b63b02",
          "md5": "7a2bf5af97046058641cb4faa6a9dc56"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "costmap_2d-1.17.1-javadoc.jar",
          "url": "costmap_2d-1.17.1-javadoc.jar",
          "size": 84566,
          "sha512": "0f7405c1d6d43a3bbdb9f00803cd504179cc3a386cbd3090a2cbeeb18fc9efc290320d1c583851220f3dd0a17ae7ddca336b740b055329b126a273366aac5d79",
          "sha256": "73674b3b5247777d3ad56f19ad33d266ed6dd135a9e57b12914d6a44f08c3814",
          "sha1": "e0d728d497a3f4f65cac01c9c6829f13f9b8503e",
          "md5": "8ee82b47e642b86a95fa57b891722be0"
        }
      ]
    }
  ]
}
