{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "rviz",
    "version": "1.14.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "nav_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "sensor_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "map_msgs",
          "version": {
            "requires": "1.14.1"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_srvs",
          "version": {
            "requires": "1.11.3"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "visualization_msgs",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "rviz-1.14.4.jar",
          "url": "rviz-1.14.4.jar",
          "size": 1529,
          "sha512": "fe7ef7336a74a548585519389eab7466ae975c8c6ea6693156dfe8299cd968d54abb411f0d88e77560fd4738e3d9615b9679c6bc7b79768a8f2a44d0c676b973",
          "sha256": "c6175faed50e274b7da2689ed518a674a4c44c536a84c6cc58ad9f71b7c16c84",
          "sha1": "866c2e1d6b0b95a36bca2acea45bc877deafd751",
          "md5": "05e1dae231430a59d4512d9e7eb15248"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "nav_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "sensor_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "map_msgs",
          "version": {
            "requires": "1.14.1"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_srvs",
          "version": {
            "requires": "1.11.3"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "visualization_msgs",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "rviz-1.14.4.jar",
          "url": "rviz-1.14.4.jar",
          "size": 1529,
          "sha512": "fe7ef7336a74a548585519389eab7466ae975c8c6ea6693156dfe8299cd968d54abb411f0d88e77560fd4738e3d9615b9679c6bc7b79768a8f2a44d0c676b973",
          "sha256": "c6175faed50e274b7da2689ed518a674a4c44c536a84c6cc58ad9f71b7c16c84",
          "sha1": "866c2e1d6b0b95a36bca2acea45bc877deafd751",
          "md5": "05e1dae231430a59d4512d9e7eb15248"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rviz-1.14.4-sources.jar",
          "url": "rviz-1.14.4-sources.jar",
          "size": 1326,
          "sha512": "f5af87bd543334e1acb0c456368878ed2c3eecc405ed5b4c02b1a2116c06af8ec2f61bee06090add3057477fc16469d0d826e1852ed51ce5470480ee378b9d67",
          "sha256": "8f2efaea910631eb2b75d5b1fc0351099e902107de4e8b146da67759b299e9f9",
          "sha1": "f9038693fd746f4c468e625717046c32f1def98b",
          "md5": "b226ead13912b3d086587740ee6b4763"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rviz-1.14.4-javadoc.jar",
          "url": "rviz-1.14.4-javadoc.jar",
          "size": 88475,
          "sha512": "5bbe5d2e82c899a84a051e698beba47ef3a5aa3a7294729e3b751bf3477f6253d51acc17581f931eddc7e21b1c4e04f931f7df4e3091c84838918b98e0839a0b",
          "sha256": "2460fd71e52f2dc897a4de70010cfdac71c2c468ba9f78d19eb5fa2e21fb59d0",
          "sha1": "dd22e1ab4bff7ad0eea3aad2798d323c7f418802",
          "md5": "da2886a0790a47ab6378c848bdf3bd98"
        }
      ]
    }
  ]
}
