{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "turtle_actionlib",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "actionlib",
          "version": {
            "requires": "1.13.2"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "turtlesim",
          "version": {
            "requires": "0.10.2"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "actionlib_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        }
      ],
      "files": [
        {
          "name": "turtle_actionlib-0.2.0.jar",
          "url": "turtle_actionlib-0.2.0.jar",
          "size": 5049,
          "sha512": "33039ce9bcbe59356528a4ce8c636218f71d23b6232f6d6ac17195540836a28e7151e0d36d38531d9caea914c77705646eea9bfdfd57770ccdb67c94cecaaff4",
          "sha256": "4b35e69ddc3bf02e462f084463c077831842acaa674180d483c429dd37037768",
          "sha1": "366d9cc15dd9efe123fbba57b956c013a579e795",
          "md5": "cd2ee6b33667fe619c2b93763f4fac21"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "actionlib",
          "version": {
            "requires": "1.13.2"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "turtlesim",
          "version": {
            "requires": "0.10.2"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "actionlib_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        }
      ],
      "files": [
        {
          "name": "turtle_actionlib-0.2.0.jar",
          "url": "turtle_actionlib-0.2.0.jar",
          "size": 5049,
          "sha512": "33039ce9bcbe59356528a4ce8c636218f71d23b6232f6d6ac17195540836a28e7151e0d36d38531d9caea914c77705646eea9bfdfd57770ccdb67c94cecaaff4",
          "sha256": "4b35e69ddc3bf02e462f084463c077831842acaa674180d483c429dd37037768",
          "sha1": "366d9cc15dd9efe123fbba57b956c013a579e795",
          "md5": "cd2ee6b33667fe619c2b93763f4fac21"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "turtle_actionlib-0.2.0-sources.jar",
          "url": "turtle_actionlib-0.2.0-sources.jar",
          "size": 4245,
          "sha512": "ada3613867c055788335e4d3b27ee2f50511a4040b2e455daab0519c652180fcd4cd8da34142869e21eb1ffe851d93f905f06b7b19502e88e22327a7b8c9423c",
          "sha256": "11a0f76e5e09489258e339421244206e04c60d2145755531a43810398989664f",
          "sha1": "741fde4eb386ddf9649ab20286fcbc37081f5842",
          "md5": "25b419d3f51d41d40afcdd98dc6438c9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "turtle_actionlib-0.2.0-javadoc.jar",
          "url": "turtle_actionlib-0.2.0-javadoc.jar",
          "size": 105678,
          "sha512": "fd10cf3d3f94ee1d227da20cf3879a39a848d53754f095a341e5cecd626cd5e7a963e03d4a9553c6804a9b76b9e08c2107f5526fe5ba0b4d22a6dd5ec56e0a00",
          "sha256": "b00f3831244f84cc1cf308dee1f38bfb5079038a36c66d09a3056b46bd04af14",
          "sha1": "c4e70978458974112d67e7b21b73e6aadb65590e",
          "md5": "c9647ef0576e0fd29c81d7797452c241"
        }
      ]
    }
  ]
}
