{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "cartographer_ros_msgs",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        }
      ],
      "files": [
        {
          "name": "cartographer_ros_msgs-1.0.0.jar",
          "url": "cartographer_ros_msgs-1.0.0.jar",
          "size": 27257,
          "sha512": "87632ddfc690d49806549ec8a967203a56d63edd5a58def6017f7c9c196fb466b8fc11a85d7043ab4ad22a7db3b3cd2717d3ca1f6063b178fce549ca98c7420c",
          "sha256": "f0f744041597bb4f3c14acc321cc68802bd4712cde0364027f7b138ddd9a8210",
          "sha1": "7f912b8bc9f62c276d2a33af4ac6e75b2ed3d2eb",
          "md5": "988da0d2b5bee461f1c9099cc5fc0b04"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        }
      ],
      "files": [
        {
          "name": "cartographer_ros_msgs-1.0.0.jar",
          "url": "cartographer_ros_msgs-1.0.0.jar",
          "size": 27257,
          "sha512": "87632ddfc690d49806549ec8a967203a56d63edd5a58def6017f7c9c196fb466b8fc11a85d7043ab4ad22a7db3b3cd2717d3ca1f6063b178fce549ca98c7420c",
          "sha256": "f0f744041597bb4f3c14acc321cc68802bd4712cde0364027f7b138ddd9a8210",
          "sha1": "7f912b8bc9f62c276d2a33af4ac6e75b2ed3d2eb",
          "md5": "988da0d2b5bee461f1c9099cc5fc0b04"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cartographer_ros_msgs-1.0.0-sources.jar",
          "url": "cartographer_ros_msgs-1.0.0-sources.jar",
          "size": 23782,
          "sha512": "f5150ca1f1ea77edefe696d066b784786dcb4dafab3d524c3b03e6c16eabcc649a0b3a21b11555eaffa41e41226810e1d0470ad6f899ba207a19df0127a5e8af",
          "sha256": "4e3c432b477ec23b49512673fe1ac6f0ebdb84a699e85e3fb79019cff597ee5b",
          "sha1": "9a472e7dd680301e1ab7df1310180e500893ec2b",
          "md5": "4aa66276f9ca3a5aa6a23353dbad5158"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cartographer_ros_msgs-1.0.0-javadoc.jar",
          "url": "cartographer_ros_msgs-1.0.0-javadoc.jar",
          "size": 176335,
          "sha512": "ab0ee729b08fa805d26e7e2ee08e7c3eaf6360b15d9115001e126409f208a1bcec7782c7dc124cb6ac3abecac73d73ea366dbf73ee5cfadfaca702946f842546",
          "sha256": "de211392767457be482a9700c80725cca10cabd9acb3b046261e0a75c94eeac3",
          "sha1": "4ce6ff5064b8aeff14d89e5dd0033770bcae74be",
          "md5": "af32df247ae9ddfd6133dd6483520fc4"
        }
      ]
    }
  ]
}
