{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "actionlib",
    "version": "1.13.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "actionlib_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        }
      ],
      "files": [
        {
          "name": "actionlib-1.13.2.jar",
          "url": "actionlib-1.13.2.jar",
          "size": 12370,
          "sha512": "a563140fa663beb3c0585d3526c1fba665032f5831cb84388f67d961ba4e47324c4138179a51cd480bc88c7cb6f3d718f1a589fe40507f6bb32bb10f0c4aefb7",
          "sha256": "84c50dd7cd0ccc59846dc90bf3f0ca74518b3ff9587e16acf70386b42174e1db",
          "sha1": "91c66a332f8f2e5c5f633b14b730d7e292b59023",
          "md5": "5afd37f5ebdf7ea501a79cdf2a825a8b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "actionlib_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        }
      ],
      "files": [
        {
          "name": "actionlib-1.13.2.jar",
          "url": "actionlib-1.13.2.jar",
          "size": 12370,
          "sha512": "a563140fa663beb3c0585d3526c1fba665032f5831cb84388f67d961ba4e47324c4138179a51cd480bc88c7cb6f3d718f1a589fe40507f6bb32bb10f0c4aefb7",
          "sha256": "84c50dd7cd0ccc59846dc90bf3f0ca74518b3ff9587e16acf70386b42174e1db",
          "sha1": "91c66a332f8f2e5c5f633b14b730d7e292b59023",
          "md5": "5afd37f5ebdf7ea501a79cdf2a825a8b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "actionlib-1.13.2-sources.jar",
          "url": "actionlib-1.13.2-sources.jar",
          "size": 10157,
          "sha512": "a634bac991a541a2b597efe65d02f7b258679a8a8d1876536f12c7689e603e0000390780e389fe70e4e0c9894634a60a97b04975a70747853f8c86128461d228",
          "sha256": "6a4df545774f56c3b706777df9e0dff4f55ad84f59bef42305d6f73ae6089625",
          "sha1": "54dfcf2c67c1789cc269833e9758c9c4b6045ef8",
          "md5": "375da792f5b739cdbfa5b1a3fb74776e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "actionlib-1.13.2-javadoc.jar",
          "url": "actionlib-1.13.2-javadoc.jar",
          "size": 144015,
          "sha512": "f3dd69e3588c05868eb7db15e0cf4b55bf2b482318c552893621c708617334bbb2a18296cdf0ca8860ae4c24dd34bc23efe5e65a4bfd9e04ea84df8b249c29f1",
          "sha256": "917188918c3138ef2b23d6f36ba067eecb66becb543b84fbc37dcaa558f2c199",
          "sha1": "b1c01db096184dd4f03477d68e37a438d97b9841",
          "md5": "fde934dfa27b6fac25a75e677ef4a52c"
        }
      ]
    }
  ]
}
