{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "rosserial_msgs",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosserial_msgs-0.9.1.jar",
          "url": "rosserial_msgs-0.9.1.jar",
          "size": 3006,
          "sha512": "ee38344dd6524ea3bfff02d089b258f3b09ef4b43decdb6ab3785b35f727e6bffdbd8cfaf1a4adf3137e6e81a677cddd65c0a8d6ca66ededc9c0d79c8cc604a0",
          "sha256": "6535efccbd01c6300dc6ca93e08c705e927024b41b19afe289d49ce7071e3bb9",
          "sha1": "4e5ea2d01c5ce540539aafdfc5a05fcba0198740",
          "md5": "b97f266ea334546cdea363ac5ae437a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosserial_msgs-0.9.1.jar",
          "url": "rosserial_msgs-0.9.1.jar",
          "size": 3006,
          "sha512": "ee38344dd6524ea3bfff02d089b258f3b09ef4b43decdb6ab3785b35f727e6bffdbd8cfaf1a4adf3137e6e81a677cddd65c0a8d6ca66ededc9c0d79c8cc604a0",
          "sha256": "6535efccbd01c6300dc6ca93e08c705e927024b41b19afe289d49ce7071e3bb9",
          "sha1": "4e5ea2d01c5ce540539aafdfc5a05fcba0198740",
          "md5": "b97f266ea334546cdea363ac5ae437a5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosserial_msgs-0.9.1-sources.jar",
          "url": "rosserial_msgs-0.9.1-sources.jar",
          "size": 2483,
          "sha512": "eebd5665781c53e23751c958d5b508844cd3e78ce3ec2fab48afe56b5b5f1e0362f916613c60e5afae3885379b03cc729421413d0846ce96b3aafc4404ea7df6",
          "sha256": "76f1997838350942f624316038ff01a721e918b4443899300032da341a7935a7",
          "sha1": "2288e31a3a69821f9b93e777086d02fd92bee1e9",
          "md5": "5db07edef1044be6fc248aa78f6627fd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosserial_msgs-0.9.1-javadoc.jar",
          "url": "rosserial_msgs-0.9.1-javadoc.jar",
          "size": 96325,
          "sha512": "91c0b307f368c16bd5b0149105555b2411dc74d7d2aefdd6bb8d536bebc3bd13c1c12cc4f9d9fcab1ee3a1160ad460a63d1cc5b1f1aa631d823b1eb5aff84942",
          "sha256": "0e2591779cd5fee8e8ff6e73e35ebd4305360250962f1767b6a318df3032f931",
          "sha1": "5bc2781e3de1587c59338f97f43acb0dc1f8e548",
          "md5": "cfbc6b7a5017ecdb107fb35a0c09efc3"
        }
      ]
    }
  ]
}
