{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "tf",
    "version": "1.13.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "sensor_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        }
      ],
      "files": [
        {
          "name": "tf-1.13.2.jar",
          "url": "tf-1.13.2.jar",
          "size": 1808,
          "sha512": "ce7656ab592626bf5c3d9543e957fa8c3f87de4d84b7c0ab33c6775c94dcbd325dec30947125fb7ad09dd653663c3643b66c868f9534d17ca22cd1eee3f0c179",
          "sha256": "4c2f7b84e009f496965948a2df3d481d3317683b0bd064544afbfaf29e27e119",
          "sha1": "2b1fadbd8b17cfc1e0cfe5eb8bf6065ed7c5b880",
          "md5": "fb463b3b5cfea766275bac4c36fe937c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "sensor_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        }
      ],
      "files": [
        {
          "name": "tf-1.13.2.jar",
          "url": "tf-1.13.2.jar",
          "size": 1808,
          "sha512": "ce7656ab592626bf5c3d9543e957fa8c3f87de4d84b7c0ab33c6775c94dcbd325dec30947125fb7ad09dd653663c3643b66c868f9534d17ca22cd1eee3f0c179",
          "sha256": "4c2f7b84e009f496965948a2df3d481d3317683b0bd064544afbfaf29e27e119",
          "sha1": "2b1fadbd8b17cfc1e0cfe5eb8bf6065ed7c5b880",
          "md5": "fb463b3b5cfea766275bac4c36fe937c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tf-1.13.2-sources.jar",
          "url": "tf-1.13.2-sources.jar",
          "size": 1499,
          "sha512": "215b11e845ee26eafcf4626b54eedb8e7228f2f22693f66b4419fef453fe6ee0c55a764f59f150bb1e2fbcef1c8ba1dd9b4b939b54c8fb273dc613fdac7b34a1",
          "sha256": "08c86095736d1157d3bd50e85bc5c2432956e1b089d6ed5f4548687ad8ff7636",
          "sha1": "526185dc9d31894bddb567fb3d1c953af2e2c0d2",
          "md5": "e62718e1b509df36711860489f0aa61f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tf-1.13.2-javadoc.jar",
          "url": "tf-1.13.2-javadoc.jar",
          "size": 90558,
          "sha512": "eb8d06a4279cefa05718cd350a0fc91e67a5c646e1b0fa3dfd08761caf4b5671f2481aec11b2e1375c7e50c257de28cce6fc5a876e22cf08ba4fa02c2ad91873",
          "sha256": "73ad2fb2d90ce17008dce93a0db4e6b8561bd62bcd372ce9fa6dcfce6edfaf42",
          "sha1": "80414c8b06dcdabee65783499cc33d738d4ad8e4",
          "md5": "474bfeeffb725e40b6b81bb31e8f98c1"
        }
      ]
    }
  ]
}
