{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "gazebo_msgs",
    "version": "2.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "sensor_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_srvs",
          "version": {
            "requires": "1.11.3"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "trajectory_msgs",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "gazebo_msgs-2.9.1.jar",
          "url": "gazebo_msgs-2.9.1.jar",
          "size": 46815,
          "sha512": "55c903fd89004914eaf2a8f7b5622063480774388c2f0c9bef65cb989ee03cae27ce514726d2038184dd3c39ffb5d57b6cb7d869a70e1fc2f4fd71f7cabe651a",
          "sha256": "763dd21ef91c809bc9858721875fbb7afeaad38bfefb397a01797d39546e3b5a",
          "sha1": "d22ec3218a5e31fe745895a437b31de6a871d124",
          "md5": "e4937a7748108f15f634c3307ddda387"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "sensor_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_srvs",
          "version": {
            "requires": "1.11.3"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "trajectory_msgs",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "gazebo_msgs-2.9.1.jar",
          "url": "gazebo_msgs-2.9.1.jar",
          "size": 46815,
          "sha512": "55c903fd89004914eaf2a8f7b5622063480774388c2f0c9bef65cb989ee03cae27ce514726d2038184dd3c39ffb5d57b6cb7d869a70e1fc2f4fd71f7cabe651a",
          "sha256": "763dd21ef91c809bc9858721875fbb7afeaad38bfefb397a01797d39546e3b5a",
          "sha1": "d22ec3218a5e31fe745895a437b31de6a871d124",
          "md5": "e4937a7748108f15f634c3307ddda387"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gazebo_msgs-2.9.1-sources.jar",
          "url": "gazebo_msgs-2.9.1-sources.jar",
          "size": 39082,
          "sha512": "24fa7762f1b0b34bd4548e1c09cd9f0da6146bde5f0a04af67fbedadcb0dda9aacc78bf7eb5305c1b8587f651c669d9c0a8772a7c677d8ec41786ade0e9196da",
          "sha256": "d06d3064ea8585e78ee0bb2970012af8c7444afc71de3a35d237dc8c61468e54",
          "sha1": "a025d11a2eca06b98937ca59988221877b9bb292",
          "md5": "67f127ea91027816e608cef65eb2c384"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gazebo_msgs-2.9.1-javadoc.jar",
          "url": "gazebo_msgs-2.9.1-javadoc.jar",
          "size": 293235,
          "sha512": "24ae4fbd711285122c8e6ae8666376b8e0a2b628e1d0a6d4afb4e973f7bbbb292b3fca6ee05db1184e72fbb6b3c8ad5b2b9a69bd89f6e5d51fe7ea77a51ee843",
          "sha256": "85758cb58a0da26420394744e16b29c40d73d7cbded701df19e800aa265a4da9",
          "sha1": "a0a08d17d2a8c271b78804441ad01d9e94092ec2",
          "md5": "c2b7e0a9195689dca647307f28ec3d55"
        }
      ]
    }
  ]
}
