{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "move_base_msgs",
    "version": "1.14.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "actionlib_msgs",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "move_base_msgs-1.14.1.jar",
          "url": "move_base_msgs-1.14.1.jar",
          "size": 4973,
          "sha512": "7d277a901487f412fdb260d3f3efdfcfdbe4b7cf5afffd1140fcdf4ce7efd8d7b26d615c3fcc00cf9e1d90ea7e00efc3d7f8e9eb904944dd415afd790ebb7716",
          "sha256": "79b5a5731f9eb907ed347641b18be5b8b98cb750183615745f34dfded53ea6c4",
          "sha1": "5b8f133ec551bf4712e8357afbc20d6094493497",
          "md5": "27c605e8216b77358b4ff0201d2baef4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "actionlib_msgs",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "move_base_msgs-1.14.1.jar",
          "url": "move_base_msgs-1.14.1.jar",
          "size": 4973,
          "sha512": "7d277a901487f412fdb260d3f3efdfcfdbe4b7cf5afffd1140fcdf4ce7efd8d7b26d615c3fcc00cf9e1d90ea7e00efc3d7f8e9eb904944dd415afd790ebb7716",
          "sha256": "79b5a5731f9eb907ed347641b18be5b8b98cb750183615745f34dfded53ea6c4",
          "sha1": "5b8f133ec551bf4712e8357afbc20d6094493497",
          "md5": "27c605e8216b77358b4ff0201d2baef4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "move_base_msgs-1.14.1-sources.jar",
          "url": "move_base_msgs-1.14.1-sources.jar",
          "size": 4141,
          "sha512": "94d1d978cbaf0cf12734341ac682891530179a77571207fe47f3ba3751f99ec66104259b831485a5fae85b2f24af58155c660c1b18ba4849c7aaf612f2e139bf",
          "sha256": "fcbe8389b49bed2a779e34b196351b651babcd61bf12c27549f053ec7d417b69",
          "sha1": "d3cfb76917e520121e5534845201af3a25339729",
          "md5": "28cc7d494eb590672476287c20c43a21"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "move_base_msgs-1.14.1-javadoc.jar",
          "url": "move_base_msgs-1.14.1-javadoc.jar",
          "size": 105420,
          "sha512": "d42db6aa592ad2db0aa40cfe05d26a38c287ddb6d9039c0b35437ebc9fd6885bee68e4271c46f60f31c7ff121a443329868607391d9a0d01cd71bbe98f1db4db",
          "sha256": "51f06d7dedb04c23eb592f931843f85af99e5de09ac576226c7fbd7ddec2df8a",
          "sha1": "92b11b17683392ddd4b293931f76f1db4bc6a736",
          "md5": "df2d4dbc4b0a43bf426866e5d862b80e"
        }
      ]
    }
  ]
}
