{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "nav_msgs",
    "version": "1.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "actionlib_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        }
      ],
      "files": [
        {
          "name": "nav_msgs-1.13.0.jar",
          "url": "nav_msgs-1.13.0.jar",
          "size": 10666,
          "sha512": "a3dc53336925c835dd8e44d9710cf6e59feb01f864a5dae45c7bc6c70b04a9fd01952bc25be205a4513a7b727a7d050029816d384eb2aad266576741713d7848",
          "sha256": "c72fade257080a6223c29adb0aa62c480016a6c8ac3a0f2d9e3083905954006f",
          "sha1": "4827307205020eec11d3457aaf54caf5802ae882",
          "md5": "13d198aa7105d4c8ef29044f4520a0f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "actionlib_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        }
      ],
      "files": [
        {
          "name": "nav_msgs-1.13.0.jar",
          "url": "nav_msgs-1.13.0.jar",
          "size": 10666,
          "sha512": "a3dc53336925c835dd8e44d9710cf6e59feb01f864a5dae45c7bc6c70b04a9fd01952bc25be205a4513a7b727a7d050029816d384eb2aad266576741713d7848",
          "sha256": "c72fade257080a6223c29adb0aa62c480016a6c8ac3a0f2d9e3083905954006f",
          "sha1": "4827307205020eec11d3457aaf54caf5802ae882",
          "md5": "13d198aa7105d4c8ef29044f4520a0f1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nav_msgs-1.13.0-sources.jar",
          "url": "nav_msgs-1.13.0-sources.jar",
          "size": 8689,
          "sha512": "8a567dac6ba5b2a9b8d85a24dda17925c66b6da8ef60630eea894518b518cd254d66dac84c6ba3b982307e358bffdb54627b022873073a3ce9172909305c39fe",
          "sha256": "50b1bd2fbfcab6ca0c2f7631e64e255bc114c740ea7aa66163b95d108f999d1f",
          "sha1": "856ef0c7ebf00c3b98ad7e8f7a51472d26323060",
          "md5": "989f30b9dc276358607c24f1d5192c7e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nav_msgs-1.13.0-javadoc.jar",
          "url": "nav_msgs-1.13.0-javadoc.jar",
          "size": 136698,
          "sha512": "2e459476772b0fb7a51a5d238388239d37506887e61c8fea9d73d2b961046298613dceace3003ccbb894dfd78de785f2f9af482845f1b319caa2a859a3505a9b",
          "sha256": "ecad37cc4e007951d4cb4f39b7dd5566b190ea0e3b44bde163e57941ab501bc0",
          "sha1": "1a3981afe067c38e0ef832610f18f3f2dbe4d729",
          "md5": "2b946a31f38216fca8b1887339149fbd"
        }
      ]
    }
  ]
}
