{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "octomap_msgs",
    "version": "0.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        }
      ],
      "files": [
        {
          "name": "octomap_msgs-0.3.5.jar",
          "url": "octomap_msgs-0.3.5.jar",
          "size": 4205,
          "sha512": "98ea86baede7693567cee3e7b8bd12874fc15653fb19a69cb9b27e14399f4cf2ade3f6575402864b811a1ae34e76d07f3ec07fdf395249d21bdc2342f7015202",
          "sha256": "41b7e5683a0b2ea9eb9ebf0a4dc2f6cfafdd5f36396c922f6d2fcfd96a3bb225",
          "sha1": "d7c41018f41b4494fb845a70516f761aab4a8466",
          "md5": "b3744fcff17b82523e61486c01036b5d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        }
      ],
      "files": [
        {
          "name": "octomap_msgs-0.3.5.jar",
          "url": "octomap_msgs-0.3.5.jar",
          "size": 4205,
          "sha512": "98ea86baede7693567cee3e7b8bd12874fc15653fb19a69cb9b27e14399f4cf2ade3f6575402864b811a1ae34e76d07f3ec07fdf395249d21bdc2342f7015202",
          "sha256": "41b7e5683a0b2ea9eb9ebf0a4dc2f6cfafdd5f36396c922f6d2fcfd96a3bb225",
          "sha1": "d7c41018f41b4494fb845a70516f761aab4a8466",
          "md5": "b3744fcff17b82523e61486c01036b5d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "octomap_msgs-0.3.5-sources.jar",
          "url": "octomap_msgs-0.3.5-sources.jar",
          "size": 3535,
          "sha512": "fb7d5713a1dc7b01e3c334f362850d0111a50574401b6f4ac08109f12b15ccd5a9177811534d9eac77a84528298c6c723c30a2db179615bb127c5cce1958a05e",
          "sha256": "c3140eb372d1ebcf6d99899f2db40edf171014cd619e15e17d9c0e3bf24d002f",
          "sha1": "24b49137239f6c1679fd908c2609d7b4b09f0358",
          "md5": "04bc800a2768d6b8769848a8ee548189"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "octomap_msgs-0.3.5-javadoc.jar",
          "url": "octomap_msgs-0.3.5-javadoc.jar",
          "size": 101703,
          "sha512": "ef5b32cd145ca162aadd099ce8e551d3f6f01045529b9dc6ecfc6bcbaeebcd68abb3e008e1026096341298a6fe0234d808c384ae749fa9bab23fdbdcf07f068c",
          "sha256": "c5f71f8568e6fe031d3fad0b30472fa76d8af87fa33feac00abe8cac9afe8d85",
          "sha1": "a16623b3459997fcc07becd1139c7098efae669b",
          "md5": "af27c9c1000218f59f3c22d7a403da46"
        }
      ]
    }
  ]
}
