{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "base_local_planner",
    "version": "1.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "nav_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "sensor_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "costmap_2d",
          "version": {
            "requires": "1.17.1"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "dynamic_reconfigure",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "visualization_msgs",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "base_local_planner-1.17.1.jar",
          "url": "base_local_planner-1.17.1.jar",
          "size": 793,
          "sha512": "57a4cea030ab09f8e605d598a2d331201ea878cff05a842977aa872cad002b24fb2309383bbf07005454120091dc6e8ad14e92b9d0a1f948c619d45a47221041",
          "sha256": "efe9a06da78416b10006dbccb5d3667b485ff3df2fea09b573f790e365480191",
          "sha1": "9b3b2e839a41e756e90fdb1eac7c232fe9f6350d",
          "md5": "745a3dde628e1d5e72a57d5b49654fbc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "nav_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "sensor_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "costmap_2d",
          "version": {
            "requires": "1.17.1"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "dynamic_reconfigure",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "visualization_msgs",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "base_local_planner-1.17.1.jar",
          "url": "base_local_planner-1.17.1.jar",
          "size": 793,
          "sha512": "57a4cea030ab09f8e605d598a2d331201ea878cff05a842977aa872cad002b24fb2309383bbf07005454120091dc6e8ad14e92b9d0a1f948c619d45a47221041",
          "sha256": "efe9a06da78416b10006dbccb5d3667b485ff3df2fea09b573f790e365480191",
          "sha1": "9b3b2e839a41e756e90fdb1eac7c232fe9f6350d",
          "md5": "745a3dde628e1d5e72a57d5b49654fbc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "base_local_planner-1.17.1-sources.jar",
          "url": "base_local_planner-1.17.1-sources.jar",
          "size": 722,
          "sha512": "b40111227be3b603f187e544b3ef54897796d8fd56d04124b41559232e9b9548a35f06bc005fbaf2a693bfc3a4e1b58db744723e708af11e665f148e59226c27",
          "sha256": "06c1e0477b01902256d4adfc59d33b8ae5846b0371573b009eb9eb89fe0673b6",
          "sha1": "12d797fe176bb63b782829fe75792de255fb493e",
          "md5": "c7b9442698924d846e1900f05a922a2c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "base_local_planner-1.17.1-javadoc.jar",
          "url": "base_local_planner-1.17.1-javadoc.jar",
          "size": 83990,
          "sha512": "b9280a17f53c7ab1e29177070c80437d3c717467665792b6ed7f9cbb6596153f26c3dfaf6b388507781f32d5f60db97baa3491c87dc12da38555a9fe0d7d07e0",
          "sha256": "4e5045f819e04425f35129773bba1ab0780a5d1e27342dc9b2708478bbd90040",
          "sha1": "97d6d34bf87f61481c08eaded3806bbe3d71eeb6",
          "md5": "33b958a0a7f406703e6115273fd63365"
        }
      ]
    }
  ]
}
