{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_core",
    "module": "rosjava",
    "version": "0.3.9.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_bootstrap",
          "module": "message_generation",
          "version": {
            "requires": "0.3.8"
          }
        }
      ],
      "files": [
        {
          "name": "rosjava-0.3.9.7.jar",
          "url": "rosjava-0.3.9.7.jar",
          "size": 309563,
          "sha512": "b6bbc5f3761dddac62835f6481f2e6663ecc9f379eed5c2a155dbf4e372b268910cb099cdb392b78270cfac5af3abf0c14f80f07639397cc6ff2d9bbdc54bf82",
          "sha256": "45983199e992543b3563c30a87673903b1fe2c8e015b6401030e7f79182244bb",
          "sha1": "f7c9cd68ca8eeb3ec8aa755d801592496ca1db8e",
          "md5": "ee0086bb5f613388df60e19887b78a01"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "rosgraph_msgs",
          "version": {
            "requires": "1.11.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.0.0-jre"
          }
        },
        {
          "group": "io.netty",
          "module": "netty",
          "version": {
            "requires": "3.10.6.Final"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.xmlrpc",
          "module": "xmlrpc-client",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.apache.xmlrpc",
          "module": "xmlrpc-common",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.apache.xmlrpc",
          "module": "xmlrpc-server",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "commons-httpclient",
          "module": "commons-httpclient",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "javax.xml.bind",
          "module": "jaxb-api",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.apache.ws.commons",
          "module": "ws-commons-util",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "dnsjava",
          "module": "dnsjava",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "commons-net",
          "module": "commons-net",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "org.ros.rosjava_bootstrap",
          "module": "message_generation",
          "version": {
            "requires": "0.3.8"
          }
        }
      ],
      "files": [
        {
          "name": "rosjava-0.3.9.7.jar",
          "url": "rosjava-0.3.9.7.jar",
          "size": 309563,
          "sha512": "b6bbc5f3761dddac62835f6481f2e6663ecc9f379eed5c2a155dbf4e372b268910cb099cdb392b78270cfac5af3abf0c14f80f07639397cc6ff2d9bbdc54bf82",
          "sha256": "45983199e992543b3563c30a87673903b1fe2c8e015b6401030e7f79182244bb",
          "sha1": "f7c9cd68ca8eeb3ec8aa755d801592496ca1db8e",
          "md5": "ee0086bb5f613388df60e19887b78a01"
        }
      ]
    }
  ]
}
