{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "rosauth",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        }
      ],
      "files": [
        {
          "name": "rosauth-1.0.1.jar",
          "url": "rosauth-1.0.1.jar",
          "size": 1903,
          "sha512": "89e75851389c797876fd1be4351aaa88dccdd8ce3f7caa6d440c42c6171d91b03c1366b63ef1c8db265d1b80b66c08bde8c2bc8c7c3e162a993d2ab86d6acd24",
          "sha256": "4c8f19ff0fd0b46b03d77ec4540a13adc1e7c700224e10ca5fbea97a3b391b8f",
          "sha1": "ba29a936e5a0ce8f6186517aab3ed88629c52ba4",
          "md5": "e8d6f8f3007d815789fe6637ec660e69"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        }
      ],
      "files": [
        {
          "name": "rosauth-1.0.1.jar",
          "url": "rosauth-1.0.1.jar",
          "size": 1903,
          "sha512": "89e75851389c797876fd1be4351aaa88dccdd8ce3f7caa6d440c42c6171d91b03c1366b63ef1c8db265d1b80b66c08bde8c2bc8c7c3e162a993d2ab86d6acd24",
          "sha256": "4c8f19ff0fd0b46b03d77ec4540a13adc1e7c700224e10ca5fbea97a3b391b8f",
          "sha1": "ba29a936e5a0ce8f6186517aab3ed88629c52ba4",
          "md5": "e8d6f8f3007d815789fe6637ec660e69"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosauth-1.0.1-sources.jar",
          "url": "rosauth-1.0.1-sources.jar",
          "size": 1643,
          "sha512": "dcd30243648c9b5252449c7127528e36efe85d4c69ad81ce06303f36c54eb6a6d498f36ac9c01c534b23087362a7a8d16aa954f4faf80ce09c23528765360a54",
          "sha256": "766c9842cb10e863e61602940c84ec8309bc62d9621a4a01725f04f7c627d507",
          "sha1": "1d74deb9f74bbfe6d59f5807a9587ad85622d66d",
          "md5": "ba2981f59e2b30b894827193eb481a26"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosauth-1.0.1-javadoc.jar",
          "url": "rosauth-1.0.1-javadoc.jar",
          "size": 89315,
          "sha512": "533809b17acfaa067bfc6f2bfea76fdd000440390b3af8bae02d81a36c030107636f061cbef2fb2e00c14f2db1584da01f5ddcf8cd3f2b7323a9e4a8592a2c6a",
          "sha256": "2cc233b0de5ade4363499d9cd85a88a985f1de65b10818b6934da506a9389275",
          "sha1": "b4f1b625adfe03d8da6b54abc920ffbc1f2ecc42",
          "md5": "5a0c9422dd81ec16fb104d81e4e8032d"
        }
      ]
    }
  ]
}
