{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "roscpp_tutorials",
    "version": "0.10.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        }
      ],
      "files": [
        {
          "name": "roscpp_tutorials-0.10.2.jar",
          "url": "roscpp_tutorials-0.10.2.jar",
          "size": 1555,
          "sha512": "9c45c59859b64e7d5b855a8002cd17b766a69894e3c715c24c6c17627fc2ac08a6343c890e2fd76d4ccad44ad909bf8608aa5460e70594278f82ccbe116b249f",
          "sha256": "a512722bf08e4c72a73ec972b0ac70d8dea32093703973666304b369bf410f3f",
          "sha1": "8fd1e8ed9c33e206f2ca256f93ffee64bec122d0",
          "md5": "29bf3462a6caa2beaec18fd7804496d1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        }
      ],
      "files": [
        {
          "name": "roscpp_tutorials-0.10.2.jar",
          "url": "roscpp_tutorials-0.10.2.jar",
          "size": 1555,
          "sha512": "9c45c59859b64e7d5b855a8002cd17b766a69894e3c715c24c6c17627fc2ac08a6343c890e2fd76d4ccad44ad909bf8608aa5460e70594278f82ccbe116b249f",
          "sha256": "a512722bf08e4c72a73ec972b0ac70d8dea32093703973666304b369bf410f3f",
          "sha1": "8fd1e8ed9c33e206f2ca256f93ffee64bec122d0",
          "md5": "29bf3462a6caa2beaec18fd7804496d1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "roscpp_tutorials-0.10.2-sources.jar",
          "url": "roscpp_tutorials-0.10.2-sources.jar",
          "size": 1357,
          "sha512": "f097e6a6b7c8e5284575a2de69a7832b1c6850751376aa493f998ae62f561fde873a95d2671f44f4c459c5bbe3917e538b0d809b8b8da8bfbf7c7c36a2dc2202",
          "sha256": "1db1d1fac717522495b00460604aa886f029cd31b9e80db5905afe9b6cc838f7",
          "sha1": "11d565da2a0b401e6b81ccf3feb5b310d297ebff",
          "md5": "fc71ccacce64cf0af293ddac10e30e85"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "roscpp_tutorials-0.10.2-javadoc.jar",
          "url": "roscpp_tutorials-0.10.2-javadoc.jar",
          "size": 88745,
          "sha512": "d5300d26e45342caeb19ed5e6137912ba8aa17ebbd9da0bc21057e767f05089eb92d8aa9ede4e0d1d69b9e5f41927282ad786864c4c4003395ba27f0be750262",
          "sha256": "44a83c24dad596295dd3d020b373411f341b3c0b7eec0d366cc345f19262ad4f",
          "sha1": "5e6d1a2efc35781990760b39e36a93cb1498ac5d",
          "md5": "c6c7a95c2839a9dc8bba56c00741d9c1"
        }
      ]
    }
  ]
}
