{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_core",
    "module": "rosjava",
    "version": "0.3.9.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 19,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_bootstrap",
          "module": "message_generation",
          "version": {
            "requires": "0.3.8"
          }
        }
      ],
      "files": [
        {
          "name": "rosjava-0.3.9.6.jar",
          "url": "rosjava-0.3.9.6.jar",
          "size": 310203,
          "sha512": "084615ecab05ccebcce22269c0746ddbd1dd78eabecd150194813b02bc2cad26b8d1fec946f41d2ea916d38fce44a877417429bc2a63d39729e9aac151da4f48",
          "sha256": "f32a20d5ef8589f5587168fdefd97fc9ef98a9e747e0ec79c42b0ee3e04f90fe",
          "sha1": "52a15b03d11472037cca2f95a08e75611edb937a",
          "md5": "0622845cdf0a301554d84eb8fc2421ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 19,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "rosgraph_msgs",
          "version": {
            "requires": "1.11.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.0.0-jre"
          }
        },
        {
          "group": "io.netty",
          "module": "netty",
          "version": {
            "requires": "3.10.6.Final"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.xmlrpc",
          "module": "xmlrpc-client",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.apache.xmlrpc",
          "module": "xmlrpc-common",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.apache.xmlrpc",
          "module": "xmlrpc-server",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "commons-httpclient",
          "module": "commons-httpclient",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "javax.xml.bind",
          "module": "jaxb-api",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.apache.ws.commons",
          "module": "ws-commons-util",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "dnsjava",
          "module": "dnsjava",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "commons-net",
          "module": "commons-net",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "org.ros.rosjava_bootstrap",
          "module": "message_generation",
          "version": {
            "requires": "0.3.8"
          }
        }
      ],
      "files": [
        {
          "name": "rosjava-0.3.9.6.jar",
          "url": "rosjava-0.3.9.6.jar",
          "size": 310203,
          "sha512": "084615ecab05ccebcce22269c0746ddbd1dd78eabecd150194813b02bc2cad26b8d1fec946f41d2ea916d38fce44a877417429bc2a63d39729e9aac151da4f48",
          "sha256": "f32a20d5ef8589f5587168fdefd97fc9ef98a9e747e0ec79c42b0ee3e04f90fe",
          "sha1": "52a15b03d11472037cca2f95a08e75611edb937a",
          "md5": "0622845cdf0a301554d84eb8fc2421ad"
        }
      ]
    }
  ]
}
