{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_core",
    "module": "rosjava_helpers",
    "version": "0.3.9.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosjava_helpers-0.3.9.5.jar",
          "url": "rosjava_helpers-0.3.9.5.jar",
          "size": 4257,
          "sha512": "a2fb6cacdf18610d5fa4ab2b97cd4dc57df45bfb9c50938660fa67b865907aad5bc44877df75f1f98f49ba6cf963d3c06dc94b62de4caff1752328ca63f44574",
          "sha256": "1fc0cd124d2e2f351a88693aae9ceb696377d256b8b11cf958af1e9851e2722c",
          "sha1": "5f65c8bbcea4cae68517df82e79aebe4975bc06c",
          "md5": "876624c7cceae4e6091530199f92d10d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_core",
          "module": "rosjava",
          "version": {
            "requires": "0.3.9.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.0.0-jre"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "rosjava_helpers-0.3.9.5.jar",
          "url": "rosjava_helpers-0.3.9.5.jar",
          "size": 4257,
          "sha512": "a2fb6cacdf18610d5fa4ab2b97cd4dc57df45bfb9c50938660fa67b865907aad5bc44877df75f1f98f49ba6cf963d3c06dc94b62de4caff1752328ca63f44574",
          "sha256": "1fc0cd124d2e2f351a88693aae9ceb696377d256b8b11cf958af1e9851e2722c",
          "sha1": "5f65c8bbcea4cae68517df82e79aebe4975bc06c",
          "md5": "876624c7cceae4e6091530199f92d10d"
        }
      ]
    }
  ]
}
