{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "object_recognition_msgs",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "actionlib_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "sensor_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "shape_msgs",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "object_recognition_msgs-0.4.2.jar",
          "url": "object_recognition_msgs-0.4.2.jar",
          "size": 11443,
          "sha512": "c8bb2d73c1258e757727c2cf0282e2e12da8219f5b63569d9051f20d74a7786d8082594cea2434fcfef14c8838bfd21eddf0029f8a9469f762d208114449baa1",
          "sha256": "6ca25d68fb5b646c3199943d480950714ffdc34f5d54fb50bc8dbd5235124bf2",
          "sha1": "156008abee259439bb2a0cd349c28da6f4aba47b",
          "md5": "7b7559f3d7808a7f26e60e82e544938b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "actionlib_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "sensor_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "shape_msgs",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "object_recognition_msgs-0.4.2.jar",
          "url": "object_recognition_msgs-0.4.2.jar",
          "size": 11443,
          "sha512": "c8bb2d73c1258e757727c2cf0282e2e12da8219f5b63569d9051f20d74a7786d8082594cea2434fcfef14c8838bfd21eddf0029f8a9469f762d208114449baa1",
          "sha256": "6ca25d68fb5b646c3199943d480950714ffdc34f5d54fb50bc8dbd5235124bf2",
          "sha1": "156008abee259439bb2a0cd349c28da6f4aba47b",
          "md5": "7b7559f3d7808a7f26e60e82e544938b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "object_recognition_msgs-0.4.2-sources.jar",
          "url": "object_recognition_msgs-0.4.2-sources.jar",
          "size": 9703,
          "sha512": "0aa526e4ee83fb5e636a9936ce9875ff1420028dd0438f98f80b30785730089fba0fb366e6e41103ccde0f7fe09e0049b2911a2833227aa138f0d7fc2dfac4d6",
          "sha256": "16f1006fe61c0462898ca512f7c55820142305fb6d4d2c2669253e7ccdabcb7d",
          "sha1": "eeb4e1aab543be119df5faf8599407c8a67213c0",
          "md5": "e3dba1fe651b40e5a0dd12a93b6c163e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "object_recognition_msgs-0.4.2-javadoc.jar",
          "url": "object_recognition_msgs-0.4.2-javadoc.jar",
          "size": 130916,
          "sha512": "6390b9f22e7d076931bbdcb01ea2e6bbeed53890df812a1cb3cb676799f65b3065509f5ed22d06fab8a87691b70c1d93a6122d8704afd1152c2fd14fff4f4540",
          "sha256": "77d449c951bd7d0a60d7431594564d42dd7c3bae204b3a94dfb16fdb268d3a4a",
          "sha1": "583585cf8eb48492b0c57a84bafafe1dbee87eeb",
          "md5": "47ad2616460dbdd138e3a78df8ced4c0"
        }
      ]
    }
  ]
}
