{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "stereo_msgs",
    "version": "1.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "sensor_msgs",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "stereo_msgs-1.13.0.jar",
          "url": "stereo_msgs-1.13.0.jar",
          "size": 1502,
          "sha512": "d8456810d9276591fac4557acfe8ae89d67855232a5fbe13c05d5c46e019666528d935a5f3029baa34167ee66f249b7ecc78635e495d5b26091b792dc9ed3924",
          "sha256": "d66b259520e4e42a0f884f4f69d538dbea71a967486479a6ef826c1a11971e23",
          "sha1": "3573084a970c326207d59e634b831d1911e233c4",
          "md5": "2966e4d85e64cc5793e8ee999ffc61e9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "sensor_msgs",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "stereo_msgs-1.13.0.jar",
          "url": "stereo_msgs-1.13.0.jar",
          "size": 1502,
          "sha512": "d8456810d9276591fac4557acfe8ae89d67855232a5fbe13c05d5c46e019666528d935a5f3029baa34167ee66f249b7ecc78635e495d5b26091b792dc9ed3924",
          "sha256": "d66b259520e4e42a0f884f4f69d538dbea71a967486479a6ef826c1a11971e23",
          "sha1": "3573084a970c326207d59e634b831d1911e233c4",
          "md5": "2966e4d85e64cc5793e8ee999ffc61e9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "stereo_msgs-1.13.0-sources.jar",
          "url": "stereo_msgs-1.13.0-sources.jar",
          "size": 1333,
          "sha512": "41a30344f74443630bb4876bba2fd0fec1f9272528747453646c6284d5ab2a41cf66af121f139300c674a9c3266aab61e4ec0f11f19a9b79fe842b3296b19eac",
          "sha256": "479fdc0e962980242b7f9d663da5092ead8977ec565fe750b46ab1fe6ab1e8ff",
          "sha1": "0c388816fef801bb0469d8456c6d834be97cf4f9",
          "md5": "573ab72902d305612fc04174757851f2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "stereo_msgs-1.13.0-javadoc.jar",
          "url": "stereo_msgs-1.13.0-javadoc.jar",
          "size": 85158,
          "sha512": "adbc17f769f6e4f1227a30babe72b949ca4f6be7a7d0639be7ffe34f4757d042ce43af6b4ea00735d0711e1ad2fd73d580f673942edab83fd9682ef926ac0e30",
          "sha256": "a3b6b25f6784247d9ebfbe7861b51a098e26a16c0cfffd7c8a9e403646878617",
          "sha1": "48e55b8e222e98a16b43e27a7ee222b7266471ab",
          "md5": "aafc5d46d14b188aa5bd9d14f4ff9f3c"
        }
      ]
    }
  ]
}
