{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "shape_msgs",
    "version": "1.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        }
      ],
      "files": [
        {
          "name": "shape_msgs-1.13.0.jar",
          "url": "shape_msgs-1.13.0.jar",
          "size": 2813,
          "sha512": "c834047fb13755aa479b7be4d1b5ce936aa766b29a7daef7550dda7152d66566bc14c93b6c1d8ba27a9586e575d5a14ed0b06565b4908b79636ed99ab4a4f9f6",
          "sha256": "b2ba4b2df2984057d31b7541aea7075fa325403ab59c7557fd62818e07918438",
          "sha1": "1ceac8ec07b7fe02711c0250ca5ad1c84a2ed908",
          "md5": "a56f79aba7095e55701e784df0a65ec8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        }
      ],
      "files": [
        {
          "name": "shape_msgs-1.13.0.jar",
          "url": "shape_msgs-1.13.0.jar",
          "size": 2813,
          "sha512": "c834047fb13755aa479b7be4d1b5ce936aa766b29a7daef7550dda7152d66566bc14c93b6c1d8ba27a9586e575d5a14ed0b06565b4908b79636ed99ab4a4f9f6",
          "sha256": "b2ba4b2df2984057d31b7541aea7075fa325403ab59c7557fd62818e07918438",
          "sha1": "1ceac8ec07b7fe02711c0250ca5ad1c84a2ed908",
          "md5": "a56f79aba7095e55701e784df0a65ec8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shape_msgs-1.13.0-sources.jar",
          "url": "shape_msgs-1.13.0-sources.jar",
          "size": 2401,
          "sha512": "73398706ac06c24890aaa476cde7994b67df23a6fae8cd9f74a0950f85dd41a2cb13216964ee6d6e25ebc0b1a8de28d3efd47811ae54780383b6dc93005fe3d3",
          "sha256": "13e8cd20e3d59ab97a4b06abcf32a6558fc9999e9c7cc74ba462d92e0412ee6e",
          "sha1": "d229776c809a85ba724b0c5fdefa7af7b7445698",
          "md5": "862d5b42349b17cf68fba375bdc4ab85"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shape_msgs-1.13.0-javadoc.jar",
          "url": "shape_msgs-1.13.0-javadoc.jar",
          "size": 93535,
          "sha512": "42f17be09872f5e75636abff72cf448104908ef158faeeba6ba29da97012e5cb5b48f121cae3ef74d3a74bfc7cd50bf57dcafb2a935279df5661de7ce623dcc8",
          "sha256": "8f0844d58442b7d6656d192adc9041df5e80bafd54f583437947e7af5052de4f",
          "sha1": "0ab3f9cddde0b181a876f3c3e23accf4ba09e809",
          "md5": "790095ffb5a833496a98c9767ac9aae4"
        }
      ]
    }
  ]
}
