{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "navfn",
    "version": "1.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "nav_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "sensor_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "costmap_2d",
          "version": {
            "requires": "1.17.1"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "visualization_msgs",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "navfn-1.17.1.jar",
          "url": "navfn-1.17.1.jar",
          "size": 3043,
          "sha512": "11a0a671dd95dc471848647747a6bc45f1508b5d959793972df8f749f1411c38be24b338a548fdebb0d6ce4d24f004d3f1dc92e35c50d56e07509fae5be34733",
          "sha256": "713a0304560a29f4421018743560c26d04fb6771b8b3e6488dffde072b1d407b",
          "sha1": "04844713395ea669ab3ad5e2e1dffc67c6c91f3f",
          "md5": "78afb3d3e8dca677b26e9504c727792a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "nav_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "sensor_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "costmap_2d",
          "version": {
            "requires": "1.17.1"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "visualization_msgs",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "navfn-1.17.1.jar",
          "url": "navfn-1.17.1.jar",
          "size": 3043,
          "sha512": "11a0a671dd95dc471848647747a6bc45f1508b5d959793972df8f749f1411c38be24b338a548fdebb0d6ce4d24f004d3f1dc92e35c50d56e07509fae5be34733",
          "sha256": "713a0304560a29f4421018743560c26d04fb6771b8b3e6488dffde072b1d407b",
          "sha1": "04844713395ea669ab3ad5e2e1dffc67c6c91f3f",
          "md5": "78afb3d3e8dca677b26e9504c727792a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navfn-1.17.1-sources.jar",
          "url": "navfn-1.17.1-sources.jar",
          "size": 2534,
          "sha512": "7bd26a2c5585c7ca33c5b3e02027c0ee4dc701fdb18774845fde3b8010af64836ba5afd2c011c78643cb4e0cf0f1a55cbbc62ec53bd850a2b5b2787574a19066",
          "sha256": "33588b50eb4be8682dad73dbef4756ff6ce47b725ab9975c1df70c41a29c4506",
          "sha1": "3c131148e3ac2d5fd2b0e28a8ea4bdc28bfe5fed",
          "md5": "f868661c5898375301938af40e54ff15"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navfn-1.17.1-javadoc.jar",
          "url": "navfn-1.17.1-javadoc.jar",
          "size": 96257,
          "sha512": "68d0d62f84fff99b8102679dfe5f3d8a2c061c9eb29b77942f981129b0f413f1effbc99db979bab8dcee5345776ed602bde54635b145e5cd0ab63440ed783943",
          "sha256": "1453850782a21b5567bc52835ecf866d4e25dd33de1dc9a07bcaf4a60f66fd9f",
          "sha1": "b7428e2d3e42d94fa92f92864b93e8db9d9c587e",
          "md5": "c5ba73c4c0a4a0d0c8a9fce0c784ed44"
        }
      ]
    }
  ]
}
