{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.dji",
    "module": "dji_srvs",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dji_srvs-0.1.3.jar",
          "url": "dji_srvs-0.1.3.jar",
          "size": 1959,
          "sha512": "fdf30dd660144aff7108d96477f18f7347b6530e8f48acedb9e8efefa6502fd61e5fe0d417bec164aec9871b72b1fd1dda50ce148882d45d94ba5466b11a9b78",
          "sha256": "79ab241f149f8c01a06be2a30fd7e680903992d205bf77becbfbe1af20bb652a",
          "sha1": "9926d59c449114c365ef92da2faefc9ce1952390",
          "md5": "ebab7e8b3918be89f249a4a116396325"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_core",
          "module": "rosjava",
          "version": {
            "requires": "0.3.6"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava"
            },
            {
              "group": "org.apache.ws.commons",
              "module": "ws-commons-util"
            }
          ]
        },
        {
          "group": "org.ros.rosjava_bootstrap",
          "module": "gradle_plugins",
          "version": {
            "requires": "0.3.3"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava"
            },
            {
              "group": "org.apache.ws.commons",
              "module": "ws-commons-util"
            }
          ]
        },
        {
          "group": "org.ros.rosjava_bootstrap",
          "module": "message_generation",
          "version": {
            "requires": "0.3.3"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava"
            },
            {
              "group": "org.apache.ws.commons",
              "module": "ws-commons-util"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "dji_srvs-0.1.3.jar",
          "url": "dji_srvs-0.1.3.jar",
          "size": 1959,
          "sha512": "fdf30dd660144aff7108d96477f18f7347b6530e8f48acedb9e8efefa6502fd61e5fe0d417bec164aec9871b72b1fd1dda50ce148882d45d94ba5466b11a9b78",
          "sha256": "79ab241f149f8c01a06be2a30fd7e680903992d205bf77becbfbe1af20bb652a",
          "sha1": "9926d59c449114c365ef92da2faefc9ce1952390",
          "md5": "ebab7e8b3918be89f249a4a116396325"
        }
      ]
    }
  ]
}
