{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_core",
    "module": "rosjava_helpers",
    "version": "0.3.9.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosjava_helpers-0.3.9.4.jar",
          "url": "rosjava_helpers-0.3.9.4.jar",
          "size": 4242,
          "sha512": "2cbd7e2d49bc938936de9565273832336118732af363dbca0c7f9e1e9028bc389a4f5c96242067b825f19544cc489cb0cb646670b480116899e421ce7c9b8970",
          "sha256": "19ec4b4d82898bbce237bab220867fed7e569a8cec8d486729a080e030ea4f16",
          "sha1": "3de5c4ea7f748b0406fa734f7fa944318d238bc2",
          "md5": "e8557ab976f56860b03277b205a6ad61"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_core",
          "module": "rosjava",
          "version": {
            "requires": "0.3.9.4"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.0.0-jre"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "rosjava_helpers-0.3.9.4.jar",
          "url": "rosjava_helpers-0.3.9.4.jar",
          "size": 4242,
          "sha512": "2cbd7e2d49bc938936de9565273832336118732af363dbca0c7f9e1e9028bc389a4f5c96242067b825f19544cc489cb0cb646670b480116899e421ce7c9b8970",
          "sha256": "19ec4b4d82898bbce237bab220867fed7e569a8cec8d486729a080e030ea4f16",
          "sha1": "3de5c4ea7f748b0406fa734f7fa944318d238bc2",
          "md5": "e8557ab976f56860b03277b205a6ad61"
        }
      ]
    }
  ]
}
