{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_core",
    "module": "rosjava_helpers",
    "version": "0.3.9.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosjava_helpers-0.3.9.4.jar",
          "url": "rosjava_helpers-0.3.9.4.jar",
          "size": 4257,
          "sha512": "61cfe86290bdb8cfa16a339d45b022b32dd96e7d46d1a24f37fa61b632ad3b303805b3cfd74088b59d2b7aa4132b8e30dcafe0fa082585d92e0aaf7a2409b6ff",
          "sha256": "306de4107fc30df1bccdd7817cab8814394800dab0be1e8c6ca5578b7c4c11e9",
          "sha1": "9413e6efb2ca76df1d0ab31c05feccf68f7512d5",
          "md5": "3d3c267c5c3d6bb518c75f6da16554d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_core",
          "module": "rosjava",
          "version": {
            "requires": "0.3.9.4"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.0.0-jre"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "rosjava_helpers-0.3.9.4.jar",
          "url": "rosjava_helpers-0.3.9.4.jar",
          "size": 4257,
          "sha512": "61cfe86290bdb8cfa16a339d45b022b32dd96e7d46d1a24f37fa61b632ad3b303805b3cfd74088b59d2b7aa4132b8e30dcafe0fa082585d92e0aaf7a2409b6ff",
          "sha256": "306de4107fc30df1bccdd7817cab8814394800dab0be1e8c6ca5578b7c4c11e9",
          "sha1": "9413e6efb2ca76df1d0ab31c05feccf68f7512d5",
          "md5": "3d3c267c5c3d6bb518c75f6da16554d6"
        }
      ]
    }
  ]
}
