{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_bootstrap",
    "module": "message_generation",
    "version": "noetic-0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "message_generation-noetic-0.1.jar",
          "url": "message_generation-noetic-0.1.jar",
          "size": 133196,
          "sha512": "cd3de34dda6f7fb21fef852c4c4be2975cf40c4ee7cd8534339b8e5181b97d4f24e340cfd4e1fe799726539af1767094567c62113f22ffe0b7ef06ea79f831f6",
          "sha256": "d72b3b4d28f2075646ce63a4054a1652c8355d2a5a612b4fac1f27a051dea7bc",
          "sha1": "7c7c16efd387e178f70056e43ea01e3c5be0f8f9",
          "md5": "5e53ced63421743be95a292da814aa24"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.netty",
          "module": "netty",
          "version": {
            "requires": "3.10.6.Final"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "commons-pool",
          "module": "commons-pool",
          "version": {
            "requires": "1.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "message_generation-noetic-0.1.jar",
          "url": "message_generation-noetic-0.1.jar",
          "size": 133196,
          "sha512": "cd3de34dda6f7fb21fef852c4c4be2975cf40c4ee7cd8534339b8e5181b97d4f24e340cfd4e1fe799726539af1767094567c62113f22ffe0b7ef06ea79f831f6",
          "sha256": "d72b3b4d28f2075646ce63a4054a1652c8355d2a5a612b4fac1f27a051dea7bc",
          "sha1": "7c7c16efd387e178f70056e43ea01e3c5be0f8f9",
          "md5": "5e53ced63421743be95a292da814aa24"
        }
      ]
    }
  ]
}
