{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_bootstrap",
    "module": "message_generation",
    "version": "noetic-0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "message_generation-noetic-0.1.jar",
          "url": "message_generation-noetic-0.1.jar",
          "size": 133790,
          "sha512": "a2c9d796f2a202487e1a05f4cb7245cb9689da00530afd0e4180652e3167c7e787fc0e83fdf948c0ba9da1b766cba16582689e105411294d0039eb9c63bc777c",
          "sha256": "29e06a145a88833fc729be583ef489118920e48c53b9acd6f4b0c59a7c005244",
          "sha1": "9b4b26f4c4905c0defbe0f4ca2cc50dde08303f3",
          "md5": "6e09ba6a6edf6bf56f3924e7da5d685f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.netty",
          "module": "netty",
          "version": {
            "requires": "3.5.2.Final"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "commons-pool",
          "module": "commons-pool",
          "version": {
            "requires": "1.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "message_generation-noetic-0.1.jar",
          "url": "message_generation-noetic-0.1.jar",
          "size": 133790,
          "sha512": "a2c9d796f2a202487e1a05f4cb7245cb9689da00530afd0e4180652e3167c7e787fc0e83fdf948c0ba9da1b766cba16582689e105411294d0039eb9c63bc777c",
          "sha256": "29e06a145a88833fc729be583ef489118920e48c53b9acd6f4b0c59a7c005244",
          "sha1": "9b4b26f4c4905c0defbe0f4ca2cc50dde08303f3",
          "md5": "6e09ba6a6edf6bf56f3924e7da5d685f"
        }
      ]
    }
  ]
}
