{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_bootstrap",
    "module": "message_generation",
    "version": "noetic-0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "message_generation-noetic-0.1.jar",
          "url": "message_generation-noetic-0.1.jar",
          "size": 133790,
          "sha512": "9d97c8cd8017ed21b168a81502fc260bf00af08610227dee06f0d21aedc191539f9811ba24e8cfab892e46bd683a2e2452c993c05eac9c753a61376f7ccdc61e",
          "sha256": "13f92f5a3144c2cdddcdc2330a47f8b55bb9e0eea2d75a5af46fc6e5b97a15e7",
          "sha1": "b33d98c6c3b3765177a7e4c0913a0866bc4522b3",
          "md5": "8a738ed96dc20f93332acb0973223600"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.netty",
          "module": "netty",
          "version": {
            "requires": "3.5.2.Final"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "commons-pool",
          "module": "commons-pool",
          "version": {
            "requires": "1.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "message_generation-noetic-0.1.jar",
          "url": "message_generation-noetic-0.1.jar",
          "size": 133790,
          "sha512": "9d97c8cd8017ed21b168a81502fc260bf00af08610227dee06f0d21aedc191539f9811ba24e8cfab892e46bd683a2e2452c993c05eac9c753a61376f7ccdc61e",
          "sha256": "13f92f5a3144c2cdddcdc2330a47f8b55bb9e0eea2d75a5af46fc6e5b97a15e7",
          "sha1": "b33d98c6c3b3765177a7e4c0913a0866bc4522b3",
          "md5": "8a738ed96dc20f93332acb0973223600"
        }
      ]
    }
  ]
}
