{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "bond",
    "version": "1.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        }
      ],
      "files": [
        {
          "name": "bond-1.8.6.jar",
          "url": "bond-1.8.6.jar",
          "size": 1495,
          "sha512": "cd6332f362fab4c787090c537f60c42d3a9d1f1bbe05825422e95ccdb9952d11cb06be4de7a03415703cb79d0d2021cb7bb9c4c4ed902001f454141c89c1a648",
          "sha256": "8e6065bed803ef3630ad8ebf5ca82d6268170bf62a5c16baa7a1de3dc917d47e",
          "sha1": "1aff2d572b6f0fa7e08595034eedad4f86b4c2b3",
          "md5": "74eea547869802d24843d6a9092fe742"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        }
      ],
      "files": [
        {
          "name": "bond-1.8.6.jar",
          "url": "bond-1.8.6.jar",
          "size": 1495,
          "sha512": "cd6332f362fab4c787090c537f60c42d3a9d1f1bbe05825422e95ccdb9952d11cb06be4de7a03415703cb79d0d2021cb7bb9c4c4ed902001f454141c89c1a648",
          "sha256": "8e6065bed803ef3630ad8ebf5ca82d6268170bf62a5c16baa7a1de3dc917d47e",
          "sha1": "1aff2d572b6f0fa7e08595034eedad4f86b4c2b3",
          "md5": "74eea547869802d24843d6a9092fe742"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bond-1.8.6-sources.jar",
          "url": "bond-1.8.6-sources.jar",
          "size": 1248,
          "sha512": "7a42f88e6a40ba944c760e3af85567c9bfb3cf0ffc8e64a0cb52b0cedbb681f7bc294182164e4b4c03aca18109289ef406d83ee4e1f544409c3b3bf6726e2ac3",
          "sha256": "a58312730ac89e32f6c75f089717156b47ce99fb3c5f6563392256009f481343",
          "sha1": "6127d18f573236453e76c12b30490e793aab16da",
          "md5": "955db65d7a69336d80f785f211f6faf2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bond-1.8.6-javadoc.jar",
          "url": "bond-1.8.6-javadoc.jar",
          "size": 87223,
          "sha512": "dd94a4219501495f32d6964e2affb9988fc41ab580839f3a94d5ef28fa773926bf6a1e48d21ed1f3b9d0f27bf669eec74b98aee834c32b1f9e7dc848e081fee7",
          "sha256": "7397d9f042572099aae1e5fee315e1b096e813ebb914fba27ce0fa879fcb6dfa",
          "sha1": "d23cf69636ee7f2f76e1152bdcff5abbc8f327fb",
          "md5": "d6272f6f9bcbb56640799d311aeb14b9"
        }
      ]
    }
  ]
}
