{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "actionlib_msgs",
    "version": "1.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        }
      ],
      "files": [
        {
          "name": "actionlib_msgs-1.13.0.jar",
          "url": "actionlib_msgs-1.13.0.jar",
          "size": 2642,
          "sha512": "f6d261e7459c7c2d1afe25a5246550f5978b6a49a69c5abe2fdc8b19e7dbf05a1cf3a902891fa9e6ead4649f4edcc6c9469740d83d70a034edf582d07e12c844",
          "sha256": "40101501f406a1e2bb30a409907115155c59a295e5ed1c1ccb48194e59c4819d",
          "sha1": "925b1b6d0673ae7367e1b8800368643ddbd58f3e",
          "md5": "6f5bcb11f5a4151a519e80202c66ffb7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        }
      ],
      "files": [
        {
          "name": "actionlib_msgs-1.13.0.jar",
          "url": "actionlib_msgs-1.13.0.jar",
          "size": 2642,
          "sha512": "f6d261e7459c7c2d1afe25a5246550f5978b6a49a69c5abe2fdc8b19e7dbf05a1cf3a902891fa9e6ead4649f4edcc6c9469740d83d70a034edf582d07e12c844",
          "sha256": "40101501f406a1e2bb30a409907115155c59a295e5ed1c1ccb48194e59c4819d",
          "sha1": "925b1b6d0673ae7367e1b8800368643ddbd58f3e",
          "md5": "6f5bcb11f5a4151a519e80202c66ffb7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "actionlib_msgs-1.13.0-sources.jar",
          "url": "actionlib_msgs-1.13.0-sources.jar",
          "size": 2224,
          "sha512": "a39e06b3c06c8178f2f86e2eab0ade9e5725f564db0cb4294bb27ec0c06d4b6b835dd2267726c224e8a09dc96067413461c5993145f18bca10452a47a521914b",
          "sha256": "8228e8217312091e915c0717df4b233832dd8d95632ae8ea9822c909eff7d270",
          "sha1": "213922b98f7e796b6e5351958b1dee6384968fcb",
          "md5": "b35bc11e73e9bada73b8977207a5a3ce"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "actionlib_msgs-1.13.0-javadoc.jar",
          "url": "actionlib_msgs-1.13.0-javadoc.jar",
          "size": 91229,
          "sha512": "1c3e2ae5de1deb9be5c967947cb4ec7ba753f0f0baa63e4dec07527379eb255c9c4501d3c5ed1778671e3fdec7f807e034b7a934e9da283119f0a66cf0c29553",
          "sha256": "70c4a3f267fb2f2bddc67073271045502b2403539d7c939d50d4c092f2f104de",
          "sha1": "725ccc16f3b0cd0bff053c3f6b71bc9e1f1189a1",
          "md5": "32e2e66db19206984cb75ceda9b2162d"
        }
      ]
    }
  ]
}
