{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "control_toolbox",
    "version": "1.18.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "control_msgs",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "dynamic_reconfigure",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "control_toolbox-1.18.2.jar",
          "url": "control_toolbox-1.18.2.jar",
          "size": 1632,
          "sha512": "488d62f5324a5485f85d24c2facd28fb0a09613ea9c29b2beb53d3c87aff17c795a5ff291ce6b1c8f8985f193b44a826d8f250d65fd23e82ae25007a11699144",
          "sha256": "9fc42c40c0b9f1b0457fe29b732f1f1e226066890a6b158ee7bb6e30b691ea60",
          "sha1": "2c65186443b61d18d9eefd407a1fb80ec3bd5662",
          "md5": "e036e1c0f8e4de0c6b32f9f15dbafe8f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "control_msgs",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "dynamic_reconfigure",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "control_toolbox-1.18.2.jar",
          "url": "control_toolbox-1.18.2.jar",
          "size": 1632,
          "sha512": "488d62f5324a5485f85d24c2facd28fb0a09613ea9c29b2beb53d3c87aff17c795a5ff291ce6b1c8f8985f193b44a826d8f250d65fd23e82ae25007a11699144",
          "sha256": "9fc42c40c0b9f1b0457fe29b732f1f1e226066890a6b158ee7bb6e30b691ea60",
          "sha1": "2c65186443b61d18d9eefd407a1fb80ec3bd5662",
          "md5": "e036e1c0f8e4de0c6b32f9f15dbafe8f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "control_toolbox-1.18.2-sources.jar",
          "url": "control_toolbox-1.18.2-sources.jar",
          "size": 1420,
          "sha512": "cff9d69fbdb4f990db2d0eed13884c84b01ea2380ed97636db18327f476b02caadcaabe9d6c7668dd0b2e0acc7d6bc44e43be9e88e0cf17ff17b0562c0fc1845",
          "sha256": "d41552ec00d34dd2885e55c702a71c8310e165bcdd3d7dd46f487cfd41b59d8d",
          "sha1": "b543051dd34586f7e8d2b8a82ccd95ad243d3eb4",
          "md5": "650a4700afacfdcf02eb5d3695ac3558"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "control_toolbox-1.18.2-javadoc.jar",
          "url": "control_toolbox-1.18.2-javadoc.jar",
          "size": 88613,
          "sha512": "5bb49ce9f0227dfc1ffc86c334d56433724bf387d84a525a6691670eab9f9d36a4fb4577a7c3d5ea68d7baa4a645fc87ae36c18c46a83d585fc9ac76b2df1154",
          "sha256": "8876c8a930e8d564e9ea56e17a4d66cb6cf47f940a46697556a741cfcf48baae",
          "sha1": "4364ed71c3720efd587638bd5c4e62160a62f4e4",
          "md5": "b135049b22f1d0acf221d71cc8cb4ca1"
        }
      ]
    }
  ]
}
