{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "std_srvs",
    "version": "1.11.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "std_srvs-1.11.3.jar",
          "url": "std_srvs-1.11.3.jar",
          "size": 3854,
          "sha512": "0c5b8bffcc2254dd0b82650c5b96595c06e51c2ebead126d7536f49488f16ffd8354c83845b7f94f29e2112ebfe5f61b0622ec375d066412f39d688ac53d29d7",
          "sha256": "804b4e436a25740e412fd234ec5f78def891acc9743954e4fb937e55dc0c9118",
          "sha1": "eeca723776f9ba00ffdb25fec8ee98d27ce04962",
          "md5": "f321ddd1584e6e4b2ff12eb88e8051c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "std_srvs-1.11.3.jar",
          "url": "std_srvs-1.11.3.jar",
          "size": 3854,
          "sha512": "0c5b8bffcc2254dd0b82650c5b96595c06e51c2ebead126d7536f49488f16ffd8354c83845b7f94f29e2112ebfe5f61b0622ec375d066412f39d688ac53d29d7",
          "sha256": "804b4e436a25740e412fd234ec5f78def891acc9743954e4fb937e55dc0c9118",
          "sha1": "eeca723776f9ba00ffdb25fec8ee98d27ce04962",
          "md5": "f321ddd1584e6e4b2ff12eb88e8051c8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "std_srvs-1.11.3-sources.jar",
          "url": "std_srvs-1.11.3-sources.jar",
          "size": 3240,
          "sha512": "7b83d70103bd4ee62da54686b67ba70e31196367f1b928ac7af07e6227b9c59e5a3479be417e14a5f335eec4518a50681b1aad6f1266e44b39c0f0361615337c",
          "sha256": "bc361720e3723a457388e4108408d02e80e4c2737a27809c5246a00a8e65a59d",
          "sha1": "62f8b40afe46a530611d1cee1f676c5f49477408",
          "md5": "b079af16d58bb1437d7f76ba0b6a8794"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "std_srvs-1.11.3-javadoc.jar",
          "url": "std_srvs-1.11.3-javadoc.jar",
          "size": 101832,
          "sha512": "aeb063352f14d05f48e425e4e1b60c9eb9a9e1204be90b3f77813274e50f68125c65dc8056062c2580ff5dead17faa0b88a867ca231354cdf2cfec49c1c5f574",
          "sha256": "14a51a2aae912a84f546108dbc7dc3f371074aca7dc4f5d32619d10a13804674",
          "sha1": "e361d28a24011c38b3ea2a614cf23160a9a0d888",
          "md5": "17d4543e8d14bec2a1452ed3d612b3ea"
        }
      ]
    }
  ]
}
