{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "moveit_msgs",
    "version": "0.11.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "actionlib_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "sensor_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "object_recognition_msgs",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "octomap_msgs",
          "version": {
            "requires": "0.3.5"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "shape_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "trajectory_msgs",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "moveit_msgs-0.11.1.jar",
          "url": "moveit_msgs-0.11.1.jar",
          "size": 101508,
          "sha512": "8cadb909a7ccf224b3507e8e7baf12ee2f089c5963a6d7489059e34f338edc68f4c2e10f57504d9d061fbd2f1273a584ba9cb199c28f2028e125264d964ff348",
          "sha256": "1862a1d783dcac656d4a2d2acca295fcb9daa6c7a2a2390aa72865732567fe3e",
          "sha1": "118ec079c7d8a9ac493e8eaa266c437b3f713939",
          "md5": "35bd81340af79c33cf7e1834ecaf710e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "actionlib_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "sensor_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "object_recognition_msgs",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "octomap_msgs",
          "version": {
            "requires": "0.3.5"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "shape_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "trajectory_msgs",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "moveit_msgs-0.11.1.jar",
          "url": "moveit_msgs-0.11.1.jar",
          "size": 101508,
          "sha512": "8cadb909a7ccf224b3507e8e7baf12ee2f089c5963a6d7489059e34f338edc68f4c2e10f57504d9d061fbd2f1273a584ba9cb199c28f2028e125264d964ff348",
          "sha256": "1862a1d783dcac656d4a2d2acca295fcb9daa6c7a2a2390aa72865732567fe3e",
          "sha1": "118ec079c7d8a9ac493e8eaa266c437b3f713939",
          "md5": "35bd81340af79c33cf7e1834ecaf710e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moveit_msgs-0.11.1-sources.jar",
          "url": "moveit_msgs-0.11.1-sources.jar",
          "size": 84300,
          "sha512": "1603b7d5950a37f2085b4d217b90cd951d7183222b12753c68ef8e7f00343c18c32529dd1e9f5ec4d5cf7d0bc2007b524c1df8389172120ab7670054e57f65a7",
          "sha256": "1152098eb194588ca118692e188108b5a3beeae93e5e03d13a98579f705c5167",
          "sha1": "f3ac948f7e353b7ffcb810a9d5bf3e95a21e38f9",
          "md5": "3d0fb7479244aa3c56e327a1a52e5310"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moveit_msgs-0.11.1-javadoc.jar",
          "url": "moveit_msgs-0.11.1-javadoc.jar",
          "size": 542007,
          "sha512": "b6db5b3e3430b252585a32271d6fef150338ab1b06634660497f0b83cfa3259c5815cad6909e57b879ea929612ca1619066e9737b471b0cf0f4d296c6f676553",
          "sha256": "67a3d2697960ba1594ece83f1dfa87cf42bc96a3c334cbc2d8105319118317e1",
          "sha1": "8f32883772e8bb26e2f47dd9abb9d74020765854",
          "md5": "76ef519644a881bdb1af728787cdb21e"
        }
      ]
    }
  ]
}
