{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "tf2_msgs",
    "version": "0.7.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "actionlib_msgs",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "tf2_msgs-0.7.5.jar",
          "url": "tf2_msgs-0.7.5.jar",
          "size": 6829,
          "sha512": "d75549eca649398a09747a3ee75d87cf8e6344dc7054d878093e79d7a79bab85a5c35829a2c210f20eda59843e07b1b0f511794ec79adc68ab5349187ce19300",
          "sha256": "28fbd76ca192d541fd41ca42bfa7520470418175f3dedf7dde44f2bd705765fd",
          "sha1": "5f099e9d109664ccc2cd1edab773c017ec158b45",
          "md5": "0dbada3358a749563b32a46d49ef1984"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "actionlib_msgs",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "tf2_msgs-0.7.5.jar",
          "url": "tf2_msgs-0.7.5.jar",
          "size": 6829,
          "sha512": "d75549eca649398a09747a3ee75d87cf8e6344dc7054d878093e79d7a79bab85a5c35829a2c210f20eda59843e07b1b0f511794ec79adc68ab5349187ce19300",
          "sha256": "28fbd76ca192d541fd41ca42bfa7520470418175f3dedf7dde44f2bd705765fd",
          "sha1": "5f099e9d109664ccc2cd1edab773c017ec158b45",
          "md5": "0dbada3358a749563b32a46d49ef1984"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tf2_msgs-0.7.5-sources.jar",
          "url": "tf2_msgs-0.7.5-sources.jar",
          "size": 5592,
          "sha512": "2a421241c680ee2cbea8263679c43ebef708cdf609dd79c7df1a2952472c2d0b97b756da2dd60d71687b1fb3dbe626b48472c5cafb950a750bfcd411638361bc",
          "sha256": "8fc548dd950505fccba87d13f297bffc6bfd0463130f0d06fd44ed7903b3f3c6",
          "sha1": "acaa3222beaa3e954cd2c65c12290d8715a3f664",
          "md5": "c8049579ec229ca44daa2dabfe90ffb6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tf2_msgs-0.7.5-javadoc.jar",
          "url": "tf2_msgs-0.7.5-javadoc.jar",
          "size": 116584,
          "sha512": "2da392cdda333b93053bdeef18af322edada55ab0b12b7b587509e8a624a656fc40661f608e381fb4cb5e09e346f59b6a732276000000ba48883504b2e7af9d1",
          "sha256": "a3825d30b8746b99fde439e30a5ffa84e14bf53c9105e7ecc373256993ef6ca4",
          "sha1": "011558c70f4d93cac10ad44fd7545d2516318dcd",
          "md5": "38769a41695a364ebb81246abcf925be"
        }
      ]
    }
  ]
}
