{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "sensor_msgs",
    "version": "1.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        }
      ],
      "files": [
        {
          "name": "sensor_msgs-1.13.0.jar",
          "url": "sensor_msgs-1.13.0.jar",
          "size": 28691,
          "sha512": "5faa0fd715f3b5cac6574f2d42ba5bc5121aa0c750e86f9aef51f83bed03ad3e6be7bef39c6a60f967915d2de9f164b7081fb8141f9fdcb5c96e825929b772ea",
          "sha256": "8d2467d923a898cc329ebaa58df213fcd49880bae53b1311370c5e2334434856",
          "sha1": "1b6a373af0cdc584a2a12ba47dbc2a1f6569c913",
          "md5": "afdb4025d8b55f05bbf57d51956ee426"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        }
      ],
      "files": [
        {
          "name": "sensor_msgs-1.13.0.jar",
          "url": "sensor_msgs-1.13.0.jar",
          "size": 28691,
          "sha512": "5faa0fd715f3b5cac6574f2d42ba5bc5121aa0c750e86f9aef51f83bed03ad3e6be7bef39c6a60f967915d2de9f164b7081fb8141f9fdcb5c96e825929b772ea",
          "sha256": "8d2467d923a898cc329ebaa58df213fcd49880bae53b1311370c5e2334434856",
          "sha1": "1b6a373af0cdc584a2a12ba47dbc2a1f6569c913",
          "md5": "afdb4025d8b55f05bbf57d51956ee426"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sensor_msgs-1.13.0-sources.jar",
          "url": "sensor_msgs-1.13.0-sources.jar",
          "size": 24453,
          "sha512": "1b24d1a61b6940278f9667c11de9dee3b0cc9efb410248868700a01354b9e97b20779dd5fc8ac36394dea3d45e32d7e9cb1c8580a016f7e7d1ff08600d1ec05f",
          "sha256": "075c6bf2b4fe610495aa4fa364d367b9bb6de765f21f383600a007459cb84df9",
          "sha1": "ae3c1026f0c24da1376ad4d50cd00d447213d4f7",
          "md5": "a27dda0eb4589581b752ec354372884d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sensor_msgs-1.13.0-javadoc.jar",
          "url": "sensor_msgs-1.13.0-javadoc.jar",
          "size": 186441,
          "sha512": "432980ec263fe66ba545bd0d72f4e9f7276d1fd4e17bb96f5565c350a46e12d024c2d80da46340dd55c4de03a2e408dc9420b26cf4f27e27f69a8bee469361fc",
          "sha256": "c90796f0205b695648f20daeefab42fcc1d78c08f9f21553ecc98ccc7faa5136",
          "sha1": "aa3cb12ca87e58b2277391f2079a8d1c8bc184ee",
          "md5": "81a072a726080b3b2567a3e3cef5a738"
        }
      ]
    }
  ]
}
