{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_core",
    "module": "rosjava_helpers",
    "version": "0.3.9.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosjava_helpers-0.3.9.2.jar",
          "url": "rosjava_helpers-0.3.9.2.jar",
          "size": 4242,
          "sha512": "d29578e151813a417437843ba5a7e6e98c51fba94596814d7b54037aa08b20bd37374681c5b9a980ad7110f9982f5a2d5f1c75e720a06e62d4e80dd0b3812150",
          "sha256": "24a9205c29b759809cdeaa01010c674ad2addb22021a970245eeaae8e9698d02",
          "sha1": "3203d5d0494fad76d6bc73dd7c9c59484d60dceb",
          "md5": "2b2657dff9de6e8c744e48cb137296b2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_core",
          "module": "rosjava",
          "version": {
            "requires": "0.3.9.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.0.0-jre"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "rosjava_helpers-0.3.9.2.jar",
          "url": "rosjava_helpers-0.3.9.2.jar",
          "size": 4242,
          "sha512": "d29578e151813a417437843ba5a7e6e98c51fba94596814d7b54037aa08b20bd37374681c5b9a980ad7110f9982f5a2d5f1c75e720a06e62d4e80dd0b3812150",
          "sha256": "24a9205c29b759809cdeaa01010c674ad2addb22021a970245eeaae8e9698d02",
          "sha1": "3203d5d0494fad76d6bc73dd7c9c59484d60dceb",
          "md5": "2b2657dff9de6e8c744e48cb137296b2"
        }
      ]
    }
  ]
}
