{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "turtlesim",
    "version": "0.10.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_srvs",
          "version": {
            "requires": "1.11.3"
          }
        }
      ],
      "files": [
        {
          "name": "turtlesim-0.10.2.jar",
          "url": "turtlesim-0.10.2.jar",
          "size": 6997,
          "sha512": "84c9222a8090e3cf73e31def65e7202005c1c6dd530fc936a4b7ad2b388e5789b83f144f88da9209ade19da70f3a6204e598ddac5d77937af12bc708c49e2d49",
          "sha256": "a9d3fd4540660985f4d39b4e96e66a7af61162b9f005d2b33ff08334118bc874",
          "sha1": "fe06bafe26ed68dac704e49b768c353223b209d4",
          "md5": "465bcfe6b5bb95103402800cd37aae8f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_srvs",
          "version": {
            "requires": "1.11.3"
          }
        }
      ],
      "files": [
        {
          "name": "turtlesim-0.10.2.jar",
          "url": "turtlesim-0.10.2.jar",
          "size": 6997,
          "sha512": "84c9222a8090e3cf73e31def65e7202005c1c6dd530fc936a4b7ad2b388e5789b83f144f88da9209ade19da70f3a6204e598ddac5d77937af12bc708c49e2d49",
          "sha256": "a9d3fd4540660985f4d39b4e96e66a7af61162b9f005d2b33ff08334118bc874",
          "sha1": "fe06bafe26ed68dac704e49b768c353223b209d4",
          "md5": "465bcfe6b5bb95103402800cd37aae8f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "turtlesim-0.10.2-sources.jar",
          "url": "turtlesim-0.10.2-sources.jar",
          "size": 5788,
          "sha512": "f8bbea38dd8e72a0328b862ce125396e09fc4b9ed6a66686dc613916c04463528a3f727f2ec1e5bd2631f38284a59d8b271c385b529eabffcab8fb7d06567ac6",
          "sha256": "43e4f19765169716d873c76e86ee6a9398e9bbc8f8b0910628464b1b29e90545",
          "sha1": "c26e5a2348286fb216a47c95375bc0852c1459a1",
          "md5": "bbfcc598786c6023a0c1e446abedba21"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "turtlesim-0.10.2-javadoc.jar",
          "url": "turtlesim-0.10.2-javadoc.jar",
          "size": 122185,
          "sha512": "275ce67872d7e13d1aeda91cf88a3a66dc27f0daef7b2543b027a6c008d8f3218779e3dd280232a80f0b88ee8500b0a0d155a5c29a6284377a51d5cc02a4e38a",
          "sha256": "9c208d806f2fd486812d0efcb7ed7ec465fac1173882f1bf1c220d910ad34b25",
          "sha1": "321b38c799584a85ba61736ec0e91d0af85edcba",
          "md5": "16566e5598a288a80555df30634b56ad"
        }
      ]
    }
  ]
}
