{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "roscpp",
    "version": "1.15.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "rosgraph_msgs",
          "version": {
            "requires": "1.11.3"
          }
        }
      ],
      "files": [
        {
          "name": "roscpp-1.15.9.jar",
          "url": "roscpp-1.15.9.jar",
          "size": 3942,
          "sha512": "b71898ce1b1e8b4393277ba1bafd406b031c9e4c1009cf66cacb7c60da87dc8a832380d5821e2c922c2a6db8941d7018cbb024156bff955dcf601c13f4b12021",
          "sha256": "172c69b20ace07f1cc1b1a440c874348c8fd734c745e0f74d47911be9872d303",
          "sha1": "75661d524b3651863d162b2fb08c21227434ab14",
          "md5": "18c8e4a38b4ccca75c414a3804965ad9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "rosgraph_msgs",
          "version": {
            "requires": "1.11.3"
          }
        }
      ],
      "files": [
        {
          "name": "roscpp-1.15.9.jar",
          "url": "roscpp-1.15.9.jar",
          "size": 3942,
          "sha512": "b71898ce1b1e8b4393277ba1bafd406b031c9e4c1009cf66cacb7c60da87dc8a832380d5821e2c922c2a6db8941d7018cbb024156bff955dcf601c13f4b12021",
          "sha256": "172c69b20ace07f1cc1b1a440c874348c8fd734c745e0f74d47911be9872d303",
          "sha1": "75661d524b3651863d162b2fb08c21227434ab14",
          "md5": "18c8e4a38b4ccca75c414a3804965ad9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "roscpp-1.15.9-sources.jar",
          "url": "roscpp-1.15.9-sources.jar",
          "size": 3227,
          "sha512": "ba576118f1ea7347053a3fa9fac8d6ea697217bb809d56b7d4b1edc10c0346d16d771ad492f67f715d4a0c3a445f44ceedb0fe6c494d00d23575113a4c4a4513",
          "sha256": "600bf7d86d3a94c9e9f7cb6acabda6090c25f04b66116f6680115642185cf1e2",
          "sha1": "9bba4e9e94555f48971eef23be59e92906188c4a",
          "md5": "aecd4ac3f659d06a6e336b62f8cc24f6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "roscpp-1.15.9-javadoc.jar",
          "url": "roscpp-1.15.9-javadoc.jar",
          "size": 103924,
          "sha512": "e9d6363497fa83cfd4ba0e10dbdd69d2eb44012b8664d362521ae4cec9d3c4f09c198a5635f4abac1544ca3458623efd442db9727cf1b4384ead3ed39996cede",
          "sha256": "27ab560d33207809399e0cff14ab44596c861e55349cc2a3fa4402b8df3f85cc",
          "sha1": "cb53fdc7fe13e6ac51e5aaf8e58645cd9cbd29cc",
          "md5": "06837cacce38e1c8a5b95d12d63e7035"
        }
      ]
    }
  ]
}
