{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "graph_msgs",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        }
      ],
      "files": [
        {
          "name": "graph_msgs-0.1.0.jar",
          "url": "graph_msgs-0.1.0.jar",
          "size": 1526,
          "sha512": "b217b9888e3dfcdffb2969c83f5e76583a465eafb80250591e1fd5cb2e1a8a6c3f0396c6d41f722accd2edab9588a9918148c63c5c6ba1ccee0df98553c75052",
          "sha256": "2f79e6ace3a6e3f810e0fc0c9c23845a1360339217d3d709e471bca14f9cb35c",
          "sha1": "d0fc2c5c1c4db8848e5b1f5f7339c7832f234652",
          "md5": "f5a5606e3d6fbb35468a1678e9f45b7f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        }
      ],
      "files": [
        {
          "name": "graph_msgs-0.1.0.jar",
          "url": "graph_msgs-0.1.0.jar",
          "size": 1526,
          "sha512": "b217b9888e3dfcdffb2969c83f5e76583a465eafb80250591e1fd5cb2e1a8a6c3f0396c6d41f722accd2edab9588a9918148c63c5c6ba1ccee0df98553c75052",
          "sha256": "2f79e6ace3a6e3f810e0fc0c9c23845a1360339217d3d709e471bca14f9cb35c",
          "sha1": "d0fc2c5c1c4db8848e5b1f5f7339c7832f234652",
          "md5": "f5a5606e3d6fbb35468a1678e9f45b7f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graph_msgs-0.1.0-sources.jar",
          "url": "graph_msgs-0.1.0-sources.jar",
          "size": 1281,
          "sha512": "e612ee3fc9d29edf2a01494378cc11be0ae1d338f05e0e95952d2934b7811c4c0a793586f8bfbe021576eac5174a82a55aa20e722eb966c5b7b5f35eee6d8c86",
          "sha256": "025a9ee05aa0f88b337cdcd83a403d777fa83b0197bb38a3322765000aa6b693",
          "sha1": "dd03d23032bf5bffce44cb2ff8934ccb20a3d9c6",
          "md5": "8c7f62cb507d2800bf4b5f90601e5535"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graph_msgs-0.1.0-javadoc.jar",
          "url": "graph_msgs-0.1.0-javadoc.jar",
          "size": 87133,
          "sha512": "e9b3a9a6e294dff5514540b5f0a92d6572621f16cc5289aedee244dd05e3729d83027287398be443b61e92779e3a979f3738d4a3cb22a94c7cf67862be6f2fcc",
          "sha256": "84dc4fb16ecc6a4fdfa777fdca4286cef673e4e8acba9413b66b0623ffcd8aae",
          "sha1": "2ffba285b0e4f639bd394f1fb7e89a50bc2fe395",
          "md5": "74e4b06e4c4a550e9fcc8f0cb433acaa"
        }
      ]
    }
  ]
}
