{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "rosserial_arduino",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "rosserial_msgs",
          "version": {
            "requires": "0.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "rosserial_arduino-0.9.1.jar",
          "url": "rosserial_arduino-0.9.1.jar",
          "size": 1972,
          "sha512": "981501a47a8ec3252d7d6bb431a0b7fe0e488b324ba6c7e548eebf50fe33b1e48c2174be0f0f7b81eedcca642f1f9cb97004239473f630d17db9e60d7645c397",
          "sha256": "8588b93cfb3f1c69735455ea50856dd3e039616e99a674a0081ccf6f346eeb43",
          "sha1": "c35adf6372decab6a70d9e371d73d30359d8a9df",
          "md5": "b1409e41a1083d195290a45da303103d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "rosserial_msgs",
          "version": {
            "requires": "0.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "rosserial_arduino-0.9.1.jar",
          "url": "rosserial_arduino-0.9.1.jar",
          "size": 1972,
          "sha512": "981501a47a8ec3252d7d6bb431a0b7fe0e488b324ba6c7e548eebf50fe33b1e48c2174be0f0f7b81eedcca642f1f9cb97004239473f630d17db9e60d7645c397",
          "sha256": "8588b93cfb3f1c69735455ea50856dd3e039616e99a674a0081ccf6f346eeb43",
          "sha1": "c35adf6372decab6a70d9e371d73d30359d8a9df",
          "md5": "b1409e41a1083d195290a45da303103d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosserial_arduino-0.9.1-sources.jar",
          "url": "rosserial_arduino-0.9.1-sources.jar",
          "size": 1678,
          "sha512": "5475b3b0792b661b8abfb5514ab5d5a4b8192cf735740946c649519fe1f1793ca4f127a191472f6a68bc458ad01b2da90d088d4422f8e3a3aac7660c71344b69",
          "sha256": "021af7ef92469934ab45cb0d853ea76dc5d3284715e16a0ed581cabcda5e8fbf",
          "sha1": "e991bcbcf83db9025ab10824012fc899b42bb74f",
          "md5": "7803ad8abd1fb3d5b553aa870265286f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosserial_arduino-0.9.1-javadoc.jar",
          "url": "rosserial_arduino-0.9.1-javadoc.jar",
          "size": 91617,
          "sha512": "c56190c72748987bf118c579640d76a8d4f958d626aafd9d05304e36aa4f64cacee676185d1701a96a8ccfdbfe3e3c9e506f2a92ddd737e3dc1603f0f6709f89",
          "sha256": "08449afa53cfc06ce622ce37ad202dc801c8281010d3f41e1976a2e6973f58b7",
          "sha1": "57f3af2a28630ca4c065aee22ec3d715858c92de",
          "md5": "d1b93d17e2cfa34047f28b4f7d017a56"
        }
      ]
    }
  ]
}
