{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "robot_localization",
    "version": "2.6.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "geographic_msgs",
          "version": {
            "requires": "0.5.5"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "nav_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "sensor_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_srvs",
          "version": {
            "requires": "1.11.3"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "nodelet",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "diagnostic_msgs",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "robot_localization-2.6.8.jar",
          "url": "robot_localization-2.6.8.jar",
          "size": 8022,
          "sha512": "45505ed5c94697ca814d39349f805c44834986cdf5d023bc920d9f396745cda0ae764e001125b75828eff3a999dbb763cd61877b0aa9384c78f56220cb0bb2ec",
          "sha256": "76700eac0c852fe3c3eb4ef8f744322b0fc33222f0ab8128deba066dfd10e737",
          "sha1": "29267920affbcf66dbb3d0c671c3bf9f9bd8da04",
          "md5": "ce40f320b09bd318281085d7a33cce70"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "geographic_msgs",
          "version": {
            "requires": "0.5.5"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "nav_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "sensor_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_srvs",
          "version": {
            "requires": "1.11.3"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "nodelet",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "diagnostic_msgs",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "robot_localization-2.6.8.jar",
          "url": "robot_localization-2.6.8.jar",
          "size": 8022,
          "sha512": "45505ed5c94697ca814d39349f805c44834986cdf5d023bc920d9f396745cda0ae764e001125b75828eff3a999dbb763cd61877b0aa9384c78f56220cb0bb2ec",
          "sha256": "76700eac0c852fe3c3eb4ef8f744322b0fc33222f0ab8128deba066dfd10e737",
          "sha1": "29267920affbcf66dbb3d0c671c3bf9f9bd8da04",
          "md5": "ce40f320b09bd318281085d7a33cce70"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "robot_localization-2.6.8-sources.jar",
          "url": "robot_localization-2.6.8-sources.jar",
          "size": 6783,
          "sha512": "7c1b7fdd09b239cd5f508c349f1ccb0981e6ba83dc3e4db0a7a592122abac58b75112d69bfa7e4e7665879d9f40f45a01bd562f4aed181050d19dfe0270063a9",
          "sha256": "008674efc8dd4b4800d3ad8e159108a7bd1acac8a3d1c0f051f5879a664e76c1",
          "sha1": "36c3fae377d87af97347d26c5abc76d4f39c9bb5",
          "md5": "598e4ca9cb300f1b39f4af367dd1a889"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "robot_localization-2.6.8-javadoc.jar",
          "url": "robot_localization-2.6.8-javadoc.jar",
          "size": 125139,
          "sha512": "31bcafa10189af91e3fec26c6efea2d147a401dc82dda5867676612f6d334f894e51b17e0e0cc238d1ab4bd960723e505693aa9c59450c91f70b58be65167b37",
          "sha256": "36fe439b53160e6f379bfeef4e2634288dbf654edade38db3aad7504a38f07ef",
          "sha1": "e4809870e169607e739df4b7a8b99c48ec595982",
          "md5": "785bcc2b0d320cef92e2980c38b13219"
        }
      ]
    }
  ]
}
