{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "four_wheel_steering_msgs",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        }
      ],
      "files": [
        {
          "name": "four_wheel_steering_msgs-1.1.1.jar",
          "url": "four_wheel_steering_msgs-1.1.1.jar",
          "size": 2222,
          "sha512": "5681616a40a037d20b351874c790fda1bb38aa50666486e4f267a2b79f52c864afbb7df04db17116f9e25d6c235eefd591d1d08d57c4a48a29cabc0d5cb7de51",
          "sha256": "e24ba98df34f7900a4d334db4cd7197705bc44fd03346d91d5f3fdcb8db1037d",
          "sha1": "7890713566a347e7ea2e52dcda1aa67dc83691a2",
          "md5": "0e73bbd5579c2fc7511a8583b1f8d7e3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        }
      ],
      "files": [
        {
          "name": "four_wheel_steering_msgs-1.1.1.jar",
          "url": "four_wheel_steering_msgs-1.1.1.jar",
          "size": 2222,
          "sha512": "5681616a40a037d20b351874c790fda1bb38aa50666486e4f267a2b79f52c864afbb7df04db17116f9e25d6c235eefd591d1d08d57c4a48a29cabc0d5cb7de51",
          "sha256": "e24ba98df34f7900a4d334db4cd7197705bc44fd03346d91d5f3fdcb8db1037d",
          "sha1": "7890713566a347e7ea2e52dcda1aa67dc83691a2",
          "md5": "0e73bbd5579c2fc7511a8583b1f8d7e3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "four_wheel_steering_msgs-1.1.1-sources.jar",
          "url": "four_wheel_steering_msgs-1.1.1-sources.jar",
          "size": 1992,
          "sha512": "5dbf6e13710ea20df0d13f30705c514b2448bbc1f85a307a913ed627fb39657f515975bc76576969350dad2a3a6402129ffc748d4826fdec139a78bbd9d86220",
          "sha256": "867409a7953051f455c1d5052356d043827f39e8b453e7aee2922f44fe116a61",
          "sha1": "b34b2af616b3696858c3dc35369c048f32a21ccf",
          "md5": "20857dfe0ceb344b556037ac78a76310"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "four_wheel_steering_msgs-1.1.1-javadoc.jar",
          "url": "four_wheel_steering_msgs-1.1.1-javadoc.jar",
          "size": 88355,
          "sha512": "ff3e937afe52e66fa6c26ac4e635c5bdf8ec47f96e356584fb219c67fca4836274d7d5494d2648321a047faf6e1552b7061d3a86a9eadd996082246bf14167a1",
          "sha256": "cb96f2c5053a172d41574863b0846f853722a1fac2ccd0f18909a0e38b6ad5a7",
          "sha1": "f85dc4e705128386d6cc7de187b9a8a71c770963",
          "md5": "da53d2c0b2d623965acf2b1a70fa4847"
        }
      ]
    }
  ]
}
