{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "rosapi",
    "version": "0.11.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosapi-0.11.12.jar",
          "url": "rosapi-0.11.12.jar",
          "size": 29607,
          "sha512": "67744f109681ccb6ba4fd6a0edbbf0cf69924ff45c0b75d51a3848f957e0a87ede6ac03209cb2474fd46b3d80aefd7f101ae1758a0a78839e899a828473b475f",
          "sha256": "1775a01e456dac393b94f6e7a41daf3ad839397baf762cd84dc736aa177121ce",
          "sha1": "cf956e0c6949fc6a9e4da335c27234103168c9a8",
          "md5": "52695ba19a9984efd2e69bbffc467237"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosapi-0.11.12.jar",
          "url": "rosapi-0.11.12.jar",
          "size": 29607,
          "sha512": "67744f109681ccb6ba4fd6a0edbbf0cf69924ff45c0b75d51a3848f957e0a87ede6ac03209cb2474fd46b3d80aefd7f101ae1758a0a78839e899a828473b475f",
          "sha256": "1775a01e456dac393b94f6e7a41daf3ad839397baf762cd84dc736aa177121ce",
          "sha1": "cf956e0c6949fc6a9e4da335c27234103168c9a8",
          "md5": "52695ba19a9984efd2e69bbffc467237"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosapi-0.11.12-sources.jar",
          "url": "rosapi-0.11.12-sources.jar",
          "size": 23796,
          "sha512": "a4c0fb8e360f0c531526527bab5314fb2dc116a0fbcddf38d8b0140f38d6364a8af8296e67321b6dee628af36478bb550f8cdd6db6c6b4befe560ab5a0d9307e",
          "sha256": "068eb264e492db0ff1dc89f416a42974bbb2f66cdb3a6eab58649b07267c20fb",
          "sha1": "d8db47c2477caf7e0facc480f12201d534fcaf11",
          "md5": "5bc54a07b8ca4a520a0e8e5351d64e06"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosapi-0.11.12-javadoc.jar",
          "url": "rosapi-0.11.12-javadoc.jar",
          "size": 261797,
          "sha512": "1708eae88ae8158863aeef2ff1c9a2bfa54284d6ca7ecd33276ce73830ec40002f819d29aff09063d1ef81247027e9ce962b9913737fe3714620f27e26539a6a",
          "sha256": "3c3bb10be2e9eaa786b206b06bef39e45dac17a8d1d7dc700ce5ec43b20e8a40",
          "sha1": "0b660c589495623386aabdf09d7dc47a2b9590f3",
          "md5": "1b2b1b7e077a5e8d21ebc93928f2f973"
        }
      ]
    }
  ]
}
