{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "rosgraph_msgs",
    "version": "1.11.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        }
      ],
      "files": [
        {
          "name": "rosgraph_msgs-1.11.3.jar",
          "url": "rosgraph_msgs-1.11.3.jar",
          "size": 2633,
          "sha512": "ce8790318a129f6b3213de9ac10bd631269c7f22a4b375234938c63834d6c545e0b5e08499bddce354e18bf1b4f736f68f83ba3a5735bcde1d14fcef8a56efde",
          "sha256": "7fe2ee5dedb94e6b1b6689d09c5e69936fc4ff530ff7c258c632641e2382ff0c",
          "sha1": "0c78f4c18bf6d128ffab84d502f82986a7d2e439",
          "md5": "ab137e8b03694c75716504ea6803b4d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        }
      ],
      "files": [
        {
          "name": "rosgraph_msgs-1.11.3.jar",
          "url": "rosgraph_msgs-1.11.3.jar",
          "size": 2633,
          "sha512": "ce8790318a129f6b3213de9ac10bd631269c7f22a4b375234938c63834d6c545e0b5e08499bddce354e18bf1b4f736f68f83ba3a5735bcde1d14fcef8a56efde",
          "sha256": "7fe2ee5dedb94e6b1b6689d09c5e69936fc4ff530ff7c258c632641e2382ff0c",
          "sha1": "0c78f4c18bf6d128ffab84d502f82986a7d2e439",
          "md5": "ab137e8b03694c75716504ea6803b4d5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosgraph_msgs-1.11.3-sources.jar",
          "url": "rosgraph_msgs-1.11.3-sources.jar",
          "size": 2155,
          "sha512": "34744f7994d312e922dbf7d0cb05a8d060b7dc9ee285f4d6c01a6416dddbc5a088436f04015636920767f9691211acef0aec8a14f9b8cb48b1823b050c58ba7f",
          "sha256": "44a69ef392705443bb98c75db318c3a957471d2964fcd98a3685393c5decc86a",
          "sha1": "3a1dfaf384da937a5babe5c71f4216398f3cad0e",
          "md5": "02839a24eeeca359459f032b023a15e0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosgraph_msgs-1.11.3-javadoc.jar",
          "url": "rosgraph_msgs-1.11.3-javadoc.jar",
          "size": 92441,
          "sha512": "d5f39a619c147f00801a451b3206254224385214544bc6689f865985ab27ad5134b6ad44060c30d842c4d7feed5b18d71db1335e959e0d06a826e6a3eefe8d3c",
          "sha256": "4d3215b5afa40b3242caba8bbe62eb87f42c8a64f0daa1b31f27190fd0c63c85",
          "sha1": "916e276cedd7b7aafcdd04d6fba2c1bed04166e8",
          "md5": "5574f8d05deaa018fd4c0796a6a844f0"
        }
      ]
    }
  ]
}
