{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "map_msgs",
    "version": "1.14.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "nav_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "sensor_msgs",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "map_msgs-1.14.1.jar",
          "url": "map_msgs-1.14.1.jar",
          "size": 9794,
          "sha512": "67a836f7124025467ec5ff2a016917577823a70f286fdf5f663363affdc9d0d747796c726039e71212ec1f5e939cdc9d3297870e6255e2b787c1a08f29f902ca",
          "sha256": "5156ba2293663016087aaaff1e2a74bb376155c0e5da27666beaf805da73e56d",
          "sha1": "0e3d6621d04c36b7d1604c9a1ef323ba8ca46e5c",
          "md5": "1fba78ed87f11fe3829b02e7e5b9784a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "nav_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "sensor_msgs",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "map_msgs-1.14.1.jar",
          "url": "map_msgs-1.14.1.jar",
          "size": 9794,
          "sha512": "67a836f7124025467ec5ff2a016917577823a70f286fdf5f663363affdc9d0d747796c726039e71212ec1f5e939cdc9d3297870e6255e2b787c1a08f29f902ca",
          "sha256": "5156ba2293663016087aaaff1e2a74bb376155c0e5da27666beaf805da73e56d",
          "sha1": "0e3d6621d04c36b7d1604c9a1ef323ba8ca46e5c",
          "md5": "1fba78ed87f11fe3829b02e7e5b9784a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "map_msgs-1.14.1-sources.jar",
          "url": "map_msgs-1.14.1-sources.jar",
          "size": 8025,
          "sha512": "1423a9b3176e9e8e9cd985109ce93057f1b11f84f1e009b0c44226cff3b0f3d3f36fb447b53109771bc028a822c14ff39a1416a272d3c502f8e7c89891a3a301",
          "sha256": "73df6c4bd401555f8f12ab89bcffd0d9f2b8ad1ee1698a16ae33445c3d3f9eb9",
          "sha1": "4118f2137b20838d07d5668ed544d047ac9a5e60",
          "md5": "bed680404f7563b3df5fb24804607182"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "map_msgs-1.14.1-javadoc.jar",
          "url": "map_msgs-1.14.1-javadoc.jar",
          "size": 136545,
          "sha512": "82737820751e25f503f1c7d805e674144c50a48a6f5bfb83b1e05d4765d55f8034d412c98692d8bfa232bbb1e9ba6af8ad03b63bf691cf608eeaa7459ef1c1f7",
          "sha256": "51dafc16768ad4c53d5304388fc1d38f5aa15cf7e0687f47390b75ea8611d897",
          "sha1": "315ee35ce82ee28142f81284cd9220893fd16f40",
          "md5": "311d054ed5b840798a88f8c39281e4d9"
        }
      ]
    }
  ]
}
