{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "rosbridge_msgs",
    "version": "0.11.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        }
      ],
      "files": [
        {
          "name": "rosbridge_msgs-0.11.12.jar",
          "url": "rosbridge_msgs-0.11.12.jar",
          "size": 1277,
          "sha512": "3e6dc1b59e587b9d28f1887accbd4510ee4040e42efa9113e9e9fd8fcccd1cfeaa7333bf673bfb61ba64233375b710ee8efe3876dbd3f15ef11e34934d632a5e",
          "sha256": "7de4b760f13f4db512270102eb9bbe7c66634badc2ee6e4d1c87352f19bad56e",
          "sha1": "c8d26471fb22f25b7cee899afa3e0c3736698428",
          "md5": "5deb5bb6ef6ac818fa61dda357bf4746"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        }
      ],
      "files": [
        {
          "name": "rosbridge_msgs-0.11.12.jar",
          "url": "rosbridge_msgs-0.11.12.jar",
          "size": 1277,
          "sha512": "3e6dc1b59e587b9d28f1887accbd4510ee4040e42efa9113e9e9fd8fcccd1cfeaa7333bf673bfb61ba64233375b710ee8efe3876dbd3f15ef11e34934d632a5e",
          "sha256": "7de4b760f13f4db512270102eb9bbe7c66634badc2ee6e4d1c87352f19bad56e",
          "sha1": "c8d26471fb22f25b7cee899afa3e0c3736698428",
          "md5": "5deb5bb6ef6ac818fa61dda357bf4746"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosbridge_msgs-0.11.12-sources.jar",
          "url": "rosbridge_msgs-0.11.12-sources.jar",
          "size": 1092,
          "sha512": "5ec3527ee60056d9bb68eb54366a7fbade621e69e80be86158c997af97e1e941360141dfa5f1a0150ec1f1e95be2a2c4679f34bc93625f5ec2cb2aa3185b85f2",
          "sha256": "62319658d581ecfb29c3ace6d9a41942b8b02b8272e32850ba2e7af1fdee26e1",
          "sha1": "61ae06f7123cba746e826a72da33cc2a01793a05",
          "md5": "1e69c3f2bf70af64aeba7fd1b26efeab"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosbridge_msgs-0.11.12-javadoc.jar",
          "url": "rosbridge_msgs-0.11.12-javadoc.jar",
          "size": 86802,
          "sha512": "a10eceb644f21642be3bb84a0c4eebf492a31a7ed7989652eec2cf93b33453350714fa81d12bfa769e5cd3b9fcead43a9f3d176b50c8f3386dc579e7cf4ab97b",
          "sha256": "c5bdd1dae36018cc22a78e0100273822d746b1045aec5f2573f299c8b330f6dd",
          "sha1": "bb900feb7f2eb1cc29c477f8bf4e6eed3dc6153e",
          "md5": "0326d900afe5b228cdfb45b2be9d1c02"
        }
      ]
    }
  ]
}
