{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "geographic_msgs",
    "version": "0.5.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "uuid_msgs",
          "version": {
            "requires": "1.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "geographic_msgs-0.5.5.jar",
          "url": "geographic_msgs-0.5.5.jar",
          "size": 16150,
          "sha512": "60c22093de4c88a41891c1e0e9b709f4076ae8b92943e020248e36a07fbcfd54e13c6bbf7790bef960592de35363ad0790f26bfe8c2faef5873263b2b2aee95b",
          "sha256": "4f17b04bee8508a554b7dae535f5c05af4377db569902993ed1855c5754cfba6",
          "sha1": "bfc4c9ef083adc26dfa941f74b8726254a93854d",
          "md5": "1039bfcbb348c77b08b2444fa10f74e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "uuid_msgs",
          "version": {
            "requires": "1.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "geographic_msgs-0.5.5.jar",
          "url": "geographic_msgs-0.5.5.jar",
          "size": 16150,
          "sha512": "60c22093de4c88a41891c1e0e9b709f4076ae8b92943e020248e36a07fbcfd54e13c6bbf7790bef960592de35363ad0790f26bfe8c2faef5873263b2b2aee95b",
          "sha256": "4f17b04bee8508a554b7dae535f5c05af4377db569902993ed1855c5754cfba6",
          "sha1": "bfc4c9ef083adc26dfa941f74b8726254a93854d",
          "md5": "1039bfcbb348c77b08b2444fa10f74e2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "geographic_msgs-0.5.5-sources.jar",
          "url": "geographic_msgs-0.5.5-sources.jar",
          "size": 13249,
          "sha512": "0fc73cee225d33e9ca11f01f0c6fd6f2a4b62e453484f9bcd3e205a3607812353e77b84f948c91f3ae21a080b395adb4ece50202e7c3459b25ffa6e3aa6dfb04",
          "sha256": "deb5f6b255d747cfaa4ba296e720262b7978f9bcd60bfb7fe58282a64207b799",
          "sha1": "bf7eebce81bd19398da33e993a1be3bd607b00a5",
          "md5": "6b92916929bb3d6eab335d283b5945a4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "geographic_msgs-0.5.5-javadoc.jar",
          "url": "geographic_msgs-0.5.5-javadoc.jar",
          "size": 155676,
          "sha512": "bc5ae95fb3dfd369df34668fbbe7a6fe0d4d2e950c87712d6eeadbd3abbce99384ca1b0a36e0307eb0f05c70651aa68b43320f33ba7ccd1e80a25310581568be",
          "sha256": "93d20e60aa02edb263390588a6d19f56d8052ebfc233859c14ceccbcf134b728",
          "sha1": "1a38b2fc85da412f1fa9fca9a1211a44afc2feab",
          "md5": "894332be7fb792063e45cfa3d77d450f"
        }
      ]
    }
  ]
}
