{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "polled_camera",
    "version": "1.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "sensor_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        }
      ],
      "files": [
        {
          "name": "polled_camera-1.12.0.jar",
          "url": "polled_camera-1.12.0.jar",
          "size": 2562,
          "sha512": "c67edef6e4c5d8b3d5a4824085640c1d7467d354421758f761fbad1bb9027c9eefdf59c6d801b5a4441732a0e24bca4cd45670c494200f25f95c45874ff8e4a8",
          "sha256": "f5affb927b0ca16f7ff6149a8be63a2da2d7dec6f3fd6137fa17fee1987a4f8c",
          "sha1": "f72821d4d8259afcb590893c000bea9c1a5948d7",
          "md5": "50336fcbce16c0929087e06b72e0c52e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "sensor_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        }
      ],
      "files": [
        {
          "name": "polled_camera-1.12.0.jar",
          "url": "polled_camera-1.12.0.jar",
          "size": 2562,
          "sha512": "c67edef6e4c5d8b3d5a4824085640c1d7467d354421758f761fbad1bb9027c9eefdf59c6d801b5a4441732a0e24bca4cd45670c494200f25f95c45874ff8e4a8",
          "sha256": "f5affb927b0ca16f7ff6149a8be63a2da2d7dec6f3fd6137fa17fee1987a4f8c",
          "sha1": "f72821d4d8259afcb590893c000bea9c1a5948d7",
          "md5": "50336fcbce16c0929087e06b72e0c52e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "polled_camera-1.12.0-sources.jar",
          "url": "polled_camera-1.12.0-sources.jar",
          "size": 2234,
          "sha512": "e38a7703d84ea806b11beb612c9b93dd5c883f0dc7d0ea34082ca3e35d74ba0b15b6fb00e4d44affa531ab6cad6c05c22752cb2f129f078f6a40a70e168e5d02",
          "sha256": "0432501368c1534461590a30899ed9ddfba0ab30b86df15c657b38d705a8fa99",
          "sha1": "96bcdfb389e0def8f59a48e1a7ef28d8fe1aebf4",
          "md5": "266102107424b328c84d421cabeb666c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "polled_camera-1.12.0-javadoc.jar",
          "url": "polled_camera-1.12.0-javadoc.jar",
          "size": 89976,
          "sha512": "c4824bd854a2229e934fb976b6586c218fac2e857dfef3ebef0d88d9730b0bd272c65c4aee69bb1ebfc4d2edb9c547b6577724c65feb5d7997814ddac89ae0bb",
          "sha256": "af141eb6184a3dad577b6e5c7fee606150d852aa85b61b695814db1db52cba82",
          "sha1": "dfd1e292c7afc8ab65b2e6b515247f1052b0d29b",
          "md5": "f973f40c6e701973a33b4a234794a913"
        }
      ]
    }
  ]
}
